import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit IA for the v4 docs restructure (issue #441).
// Add new pages here when you add them under docs-site/docs/
// — the autogenerated sidebar was retired so the IA is reviewable.

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'core-concepts',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/local-setup',
        'getting-started/environment-variables',
        'getting-started/project-structure',
        'getting-started/deployment',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        {
          type: 'category',
          label: 'Core Flow',
          items: [
            'architecture/prompt-pipeline',
            'architecture/requirement-gathering-methodology',
            'architecture/harness-runtime',
            'architecture/schema-conformance',
            'architecture/arm-call-flow',
          ],
        },
        {
          type: 'category',
          label: 'Agent System',
          items: [
            'architecture/agent-coordination',
            'architecture/skill-injection',
            'architecture/tool-usage-framework',
            'architecture/component-selection-framework',
          ],
        },
        {
          type: 'category',
          label: 'Frontend & Protocol',
          items: [
            'architecture/a2ui-integration',
            'architecture/mcp-server-internals',
            'architecture/extending-a2ui',
          ],
        },
        {
          type: 'category',
          label: 'Patterns',
          items: ['architecture/patterns/track-flip'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Pack Authoring',
      items: [
        'pack-authoring/index',
        'pack-authoring/packs',
        'pack-authoring/packs-and-skills',
        'pack-authoring/llm-tools',
        'pack-authoring/mcp-tools',
        'pack-authoring/actions',
        'pack-authoring/guardrails',
        'pack-authoring/safeguards',
        'pack-authoring/api-endpoints',
        'pack-authoring/session-store',
        'pack-authoring/playground-scenarios',
        'pack-authoring/conversation-limits',
        'pack-authoring/custom-catalog',
        {
          type: 'category',
          label: 'Reference',
          items: [
            'pack-authoring/reference/tools',
            'pack-authoring/reference/skills',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Agent Authoring',
      items: [
        'agent-authoring/index',
        'agent-authoring/conversation-phases',
        'agent-authoring/agent-as-tool',
        'agent-authoring/runner-chain',
        'agent-authoring/resume-and-session-token',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/observability',
        'operations/browser-telemetry',
        'operations/csp-enforcement',
        'operations/debugging',
        'operations/troubleshooting',
      ],
    },
    'contributing',
  ],
};

export default sidebars;

