import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit IA for the v3 docs restructure. Add new pages here when you add
// them under docs-site/docs — the autogenerated sidebar was retired so the
// information architecture is reviewable.

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/local-setup',
        'getting-started/environment-variables',
        'getting-started/project-structure',
        'getting-started/deployment',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/prompt-pipeline',
        'architecture/harness-runtime',
        'architecture/a2ui-integration',
        'architecture/mcp-server-internals',
        'architecture/schema-conformance',
        'architecture/agent-coordination',
        'architecture/skill-injection',
        'architecture/component-selection-framework',
        'architecture/tool-usage-framework',
        'architecture/requirement-gathering-methodology',
        'architecture/arm-call-flow',
        {
          type: 'category',
          label: 'Patterns',
          items: ['architecture/patterns/track-flip'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Extending',
      items: [
        'extending/overview',
        'extending/packs',
        'extending/llm-tools',
        'extending/mcp-tools',
        'extending/conversation-phases',
        'extending/api-endpoints',
        'extending/session-store',
        'extending/guardrails',
        'extending/safeguards',
        'extending/actions',
        'extending/resume-and-session-token',
        'extending/playground-scenarios',
        'extending/agent-as-tool',
        'extending/runner-chain',
        'extending/tools-reference',
        'extending/skills-reference',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/custom-catalog',
        'components/extending-a2ui',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/packs-and-skills',
        'guides/conversation-limits',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/observability',
        'operations/browser-telemetry',
        'operations/debugging',
        'operations/troubleshooting',
      ],
    },
    'contributing',
  ],
};

export default sidebars;
