/**
 * @module @kickstart/web/contexts/ArtifactContext
 *
 * React context for accessing the artifact store in the browser.
 * Exposes a reactive list of artifacts so components re-render when new files
 * are generated by LLM tools (generate_kubernetes_manifest, etc.).
 *
 * Usage:
 *   <ArtifactProvider>
 *     <App />
 *   </ArtifactProvider>
 *
 *   const { artifacts, getArtifact, downloadAll } = useArtifacts();
 */
import React, { createContext, useCallback, useContext, useEffect, useRef, useState, } from 'react';
import JSZip from 'jszip';
import { defaultArtifactStore } from '@kickstart/core';
const ArtifactContext = createContext(null);
export function ArtifactProvider({ children, store: externalStore, pollIntervalMs = 1000, }) {
    const store = externalStore ?? defaultArtifactStore;
    const [artifacts, setArtifacts] = useState(() => store.list());
    const intervalRef = useRef(null);
    const refresh = useCallback(() => {
        setArtifacts(store.list());
    }, [store]);
    // Poll for new artifacts written by tools (tool execution happens outside React)
    useEffect(() => {
        if (pollIntervalMs <= 0)
            return;
        intervalRef.current = setInterval(refresh, pollIntervalMs);
        return () => {
            if (intervalRef.current !== null)
                clearInterval(intervalRef.current);
        };
    }, [refresh, pollIntervalMs]);
    const getArtifact = useCallback((path) => store.get(path), [store]);
    const downloadAll = useCallback(async () => {
        const all = store.list();
        if (all.length === 0)
            return false;
        const zip = new JSZip();
        for (const artifact of all) {
            zip.file(artifact.path, artifact.content);
        }
        const blob = await zip.generateAsync({ type: 'blob' });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.download = 'kickstart-artifacts.zip';
        document.body.appendChild(anchor);
        anchor.click();
        document.body.removeChild(anchor);
        URL.revokeObjectURL(url);
        return true;
    }, [store]);
    return (<ArtifactContext.Provider value={{ artifacts, getArtifact, downloadAll, refresh }}>
      {children}
    </ArtifactContext.Provider>);
}
/** Hook to access the artifact store from any component inside ArtifactProvider. */
export function useArtifacts() {
    const ctx = useContext(ArtifactContext);
    if (!ctx) {
        throw new Error('useArtifacts must be used inside <ArtifactProvider>');
    }
    return ctx;
}
//# sourceMappingURL=ArtifactContext.js.map