/**
 * @module @kickstart/web/contexts/ArtifactContext
 *
 * React context for accessing the artifact store in the browser.
 * Exposes a reactive list of artifacts so components re-render when new files
 * are generated by LLM tools (generate_kubernetes_manifest, etc.).
 *
 * Usage:
 *   <ArtifactProvider>
 *     <App />
 *   </ArtifactProvider>
 *
 *   const { artifacts, getArtifact, downloadAll } = useArtifacts();
 */

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import JSZip from 'jszip';
import type { ArtifactStore } from '@kickstart/harness';
import type { WebArtifact } from '../types';

interface ArtifactContextValue {
  /** Current snapshot of all stored artifacts. Refreshes after every tool call. */
  artifacts: WebArtifact[];
  /** Retrieve a single artifact by path. Returns null if not found. */
  getArtifact: (path: string) => WebArtifact | null;
  /**
   * Download all artifacts as a zip file named `kickstart-artifacts.zip`.
   * Returns false if there are no artifacts.
   */
  downloadAll: () => Promise<boolean>;
  /** Manually trigger a refresh of the artifact list. */
  refresh: () => void;
}

const ArtifactContext = createContext<ArtifactContextValue | null>(null);

interface ArtifactProviderProps {
  children: ReactNode;
  /**
   * Session-scoped ArtifactStore instance. Required — there is no singleton
   * fallback. Callers must create and pass an InMemoryArtifactStore explicitly.
   */
  store: ArtifactStore;
  /**
   * Polling interval in milliseconds for detecting new artifacts written by
   * backend tools. Defaults to 1000ms. Set to 0 to disable polling.
   */
  pollIntervalMs?: number;
}

async function materializeArtifacts(store: ArtifactStore): Promise<WebArtifact[]> {
  if (!store.list || !store.get) return [];
  const paths = await Promise.resolve(store.list());
  const getter = store.get;
  const entries = await Promise.all(
    paths.map(async (path) => {
      const content = await Promise.resolve(getter(path));
      return content == null ? null : ({ path, content } as WebArtifact);
    }),
  );
  return entries.filter((e): e is WebArtifact => e !== null);
}

function materializeArtifactsSync(store: ArtifactStore): WebArtifact[] {
  if (!store.list || !store.get) return [];
  const maybePaths = store.list();
  if (!Array.isArray(maybePaths)) return [];
  const getter = store.get;
  const out: WebArtifact[] = [];
  for (const path of maybePaths) {
    const content = getter(path);
    if (typeof content === 'string') out.push({ path, content });
  }
  return out;
}

export function ArtifactProvider({
  children,
  store,
  pollIntervalMs = 1000,
}: ArtifactProviderProps) {
  if (!store) {
    throw new Error(
      'ArtifactProvider requires a session-scoped `store` prop. ' +
      'Create an InMemoryArtifactStore and pass it explicitly.',
    );
  }
  const [artifacts, setArtifacts] = useState<WebArtifact[]>(() => materializeArtifactsSync(store));
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const refresh = useCallback(() => {
    void materializeArtifacts(store).then(setArtifacts);
  }, [store]);

  // Poll for new artifacts written by tools (tool execution happens outside React)
  useEffect(() => {
    if (pollIntervalMs <= 0) return;
    intervalRef.current = setInterval(refresh, pollIntervalMs);
    return () => {
      if (intervalRef.current !== null) clearInterval(intervalRef.current);
    };
  }, [refresh, pollIntervalMs]);

  const getArtifact = useCallback(
    (path: string): WebArtifact | null => {
      return artifacts.find((a) => a.path === path) ?? null;
    },
    [artifacts]
  );

  const downloadAll = useCallback(async (): Promise<boolean> => {
    const all = await materializeArtifacts(store);
    if (all.length === 0) return false;

    const zip = new JSZip();
    for (const artifact of all) {
      zip.file(artifact.path, artifact.content);
    }

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'kickstart-artifacts.zip';
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
    return true;
  }, [store]);

  return (
    <ArtifactContext.Provider value={{ artifacts, getArtifact, downloadAll, refresh }}>
      {children}
    </ArtifactContext.Provider>
  );
}

/** Hook to access the artifact store from any component inside ArtifactProvider. */
export function useArtifacts(): ArtifactContextValue {
  const ctx = useContext(ArtifactContext);
  if (!ctx) {
    throw new Error('useArtifacts must be used inside <ArtifactProvider>');
  }
  return ctx;
}
