/**
 * @module @kickstart/web/contexts/ArtifactContext
 *
 * React context for accessing the artifact store in the browser.
 * Exposes a reactive list of artifacts so components re-render when new files
 * are generated by LLM tools (generate_kubernetes_manifest, etc.).
 *
 * Usage:
 *   <ArtifactProvider>
 *     <App />
 *   </ArtifactProvider>
 *
 *   const { artifacts, getArtifact, downloadAll } = useArtifacts();
 */
import React, { type ReactNode } from 'react';
import type { Artifact, ArtifactStore } from '@kickstart/core';
interface ArtifactContextValue {
    /** Current snapshot of all stored artifacts. Refreshes after every tool call. */
    artifacts: Artifact[];
    /** Retrieve a single artifact by path. Returns null if not found. */
    getArtifact: (path: string) => Artifact | null;
    /**
     * Download all artifacts as a zip file named `kickstart-artifacts.zip`.
     * Returns false if there are no artifacts.
     */
    downloadAll: () => Promise<boolean>;
    /** Manually trigger a refresh of the artifact list. */
    refresh: () => void;
}
interface ArtifactProviderProps {
    children: ReactNode;
    /**
     * Optional: inject a custom ArtifactStore (useful in tests / Storybook).
     * Defaults to `defaultArtifactStore` from @kickstart/core.
     */
    store?: ArtifactStore;
    /**
     * Polling interval in milliseconds for detecting new artifacts written by
     * backend tools. Defaults to 1000ms. Set to 0 to disable polling.
     */
    pollIntervalMs?: number;
}
export declare function ArtifactProvider({ children, store: externalStore, pollIntervalMs, }: ArtifactProviderProps): React.JSX.Element;
/** Hook to access the artifact store from any component inside ArtifactProvider. */
export declare function useArtifacts(): ArtifactContextValue;
export {};
//# sourceMappingURL=ArtifactContext.d.ts.map