// Shared TypeScript types for the Kickstart chat application

export interface DebugMetadata {
  /** Model name used for this response (e.g., "gpt-4o"). */
  model?: string;
  /** Raw LLM response text before rendering. */
  rawResponse?: string;
  /** Rendering engine decisions (component choices, catalog, degradation). */
  renderDecisions?: string[];
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  surfaceIds?: string[];
  phase?: string;
  model?: string;
  timestamp: number;
  isStreaming?: boolean;
  /** When true, this message was auto-generated by the auto-continue middleware (not typed by the user). */
  isAutoContinue?: boolean;
  /** Debug metadata captured when debug mode is active. */
  debugInfo?: DebugMetadata;
}

export interface Session {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  backendSessionId?: string;
}

export type AppMode = 'landing' | 'chat';

export interface DemoResponse {
  text: string;
  a2uiMessages: A2uiMsg[];
  phase: string;
  model?: string;
  typingDelay?: number;
}

export interface A2uiMsg {
  version: 'v0.9';
  createSurface?: {
    surfaceId: string;
    catalogId: string;
    sendDataModel?: boolean;
  };
  updateComponents?: {
    surfaceId: string;
    components: A2uiComponent[];
  };
  deleteSurface?: {
    surfaceId: string;
  };
  updateDataModel?: {
    surfaceId: string;
    path: string;
    value: unknown;
  };
}

export interface A2uiComponent {
  id: string;
  component: string;
  [key: string]: unknown;
}

export interface StreamEvent {
  error?: string;
  delta?: string;
  content?: string;
  a2ui?: A2uiMsg[];
  phase?: string;
  model?: string;
  sessionId?: string;
  /** Debug-only: rendering decisions from the engine. */
  renderDecisions?: string[];
}
