// Shared TypeScript types for the Kickstart chat application

/** A logged action dispatch event for debug visibility. */
export interface ActionDebugEvent {
  /** Timestamp (ms) when the action was dispatched. */
  timestamp: number;
  /** A2UI action name (e.g. "pick-runtime", "navigate:plan"). */
  actionName: string;
  /** Routing category determined by useActionDispatch. */
  category: string;
  /** The event.context payload sent back to the LLM. */
  context: Record<string, unknown>;
  /** The natural-language message synthesised from the action. */
  outboundMessage: string;
}

export interface DebugMetadata {
  /** Model name used for this response (e.g., "gpt-4o"). */
  model?: string;
  /** Raw LLM response text before rendering. */
  rawResponse?: string;
  /** Full JSON envelope content before message extraction. */
  rawContent?: string;
  /** Complete structured envelope: text + all A2UI messages received for this turn. */
  fullEnvelope?: {
    message?: string;
    a2ui?: A2uiPayloadItem[];
    model?: string;
    phase?: string;
    usage?: TokenUsageSummary;
  };
}

export type UsageCostStatus = 'estimated' | 'unavailable';

export interface TokenUsageSnapshot {
  model: string;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  recordedAt: string;
  estimatedCostUsd?: number;
  costStatus: UsageCostStatus;
}

export interface SessionUsageTotals {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  turnCount: number;
  estimatedCostUsd?: number;
  costStatus: UsageCostStatus;
}

export interface TokenUsageSummary {
  turn: TokenUsageSnapshot;
  session: SessionUsageTotals;
}

export type ConversationPhaseId =
  | 'discover'
  | 'design'
  | 'generate'
  | 'review'
  | 'handoff'
  | 'deploy';

export interface ConversationPhaseStep {
  id: string;
  label: string;
  status: 'pending' | 'active' | 'complete';
}

export interface ConversationPhasePayload {
  type: 'ConversationPhase';
  id: string;
  phases: ConversationPhaseStep[];
  currentPhase: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  surfaceIds?: string[];
  phase?: string;
  model?: string;
  timestamp: number;
  isStreaming?: boolean;
  /** When true, this message was auto-generated by the auto-continue middleware (not typed by the user). */
  isAutoContinue?: boolean;
  /** Debug metadata captured when debug mode is active. */
  debugInfo?: DebugMetadata;
  /** Raw A2UI messages that produced the surfaces for this message (used to rehydrate on reload). */
  a2uiMessages?: A2uiPayloadItem[];
  /** Token usage captured for this assistant turn. */
  usage?: TokenUsageSnapshot;
}

export interface Session {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  backendSessionId?: string;
}

export type AppMode = 'landing' | 'chat';

export interface DemoResponse {
  text: string;
  a2uiMessages: A2uiMsg[];
  phase: string;
  model?: string;
  typingDelay?: number;
}

export interface A2uiMsg {
  version: 'v0.9';
  createSurface?: {
    surfaceId: string;
    catalogId: string;
  };
  updateComponents?: {
    surfaceId: string;
    components: A2uiComponent[];
  };
  deleteSurface?: {
    surfaceId: string;
  };
  updateDataModel?: {
    surfaceId: string;
    path: string;
    value: unknown;
  };
}

export interface A2uiComponent {
  id: string;
  component: string;
  [key: string]: unknown;
}

export type A2uiPayloadItem = A2uiMsg | ConversationPhasePayload;

export interface StreamEvent {
  error?: string;
  delta?: string;
  content?: string;
  a2ui?: A2uiPayloadItem[];
  phase?: string;
  model?: string;
  sessionId?: string;
  usage?: TokenUsageSummary;
}
