#!/usr/bin/env node
/**
 * scripts/persona-sim.ts
 *
 * AI-driven persona sim harness.
 * Instead of scripted follow-ups, each user turn is generated by an LLM
 * that has fully adopted the persona — pushing back when things are confusing,
 * picking A2UI actions when offered, always driving toward the goal.
 *
 * Goal: Deploy to AKS Automatic in < 5 minutes
 * Milestones: triage_routed -> context_loaded -> solution_shaped
 *             -> artifacts_generated -> repo_connected -> pr_created
 */
import * as fs   from 'node:fs';
import * as path from 'node:path';
import * as cp   from 'node:child_process';
import { parseArgs } from 'node:util';
import OpenAI from 'openai';

const { values: args } = parseArgs({
  options: {
    personas: { type: 'string' },  // comma-separated persona ids to run (legacy)
    count:    { type: 'string' },  // number of random personas to generate (default 3)
    turns:    { type: 'string' },  // max turns per persona (default 20)
  },
  strict: false,
});

const REPORTS_DIR    = path.join(process.cwd(), 'reports');
const PROBE_CMD      = 'npx tsx --tsconfig tsconfig.scripts.json scripts/probe.ts';
const GOAL_BUDGET_MS = 5 * 60 * 1000;
const MAX_TURNS      = parseInt(args.turns ?? '20', 10);

// ---------------------------------------------------------------------------
// Persona type
// ---------------------------------------------------------------------------

interface Persona {
  id:          string;
  name:        string;
  title:       string;
  description: string; // full system prompt for the persona LLM
  opener:      string; // the very first message they send
}

// ---------------------------------------------------------------------------
// Persona generation
// ---------------------------------------------------------------------------

const INSPIRATION_DOMAINS = [
  'fitness & wellness', 'food & cooking', 'education & learning', 'travel & local discovery',
  'productivity & focus', 'sustainability & environment', 'social & community', 'finance & budgeting',
  'music & audio', 'gaming & entertainment', 'health & mental wellness', 'sports & analytics',
  'IoT & smart home', 'creative arts & design', 'HR & recruitment', 'pets & animal care',
];

async function generateAppIdea(client: OpenAI): Promise<string> {
  const domain = INSPIRATION_DOMAINS[Math.floor(Math.random() * INSPIRATION_DOMAINS.length)];
  const resp = await client.chat.completions.create({
    model: process.env.KICKSTART_INSPIRE_MODEL ?? process.env.KICKSTART_CHAT_MODEL ?? 'gpt-5.4-mini',
    messages: [
      { role: 'system', content: `You generate a single creative app idea for a developer to build and deploy to the cloud. Be original. Never suggest todo apps, weather dashboards, or plain chat bots. The idea must require a server-side component (API, database, or AI service). Return ONLY a JSON object with "prompt": a first-person sentence starting with "I want to build". No markdown, raw JSON only.` },
      { role: 'user', content: `Generate 1 creative app idea in the "${domain}" space. Surprise me.` },
    ],
    max_completion_tokens: 120,
    temperature: 1.0,
  });
  const raw = resp.choices[0]?.message?.content?.trim() ?? '{}';
  try {
    const parsed = JSON.parse(raw) as { prompt?: string };
    return parsed.prompt ?? `I want to build a ${domain} app`;
  } catch {
    return `I want to build a ${domain} app`;
  }
}

async function generatePersonas(client: OpenAI, count: number): Promise<Persona[]> {
  process.stderr.write(`[Personas] Generating ${count} random persona(s) via LLM...\n`);

  const seed = Math.floor(Math.random() * 1_000_000);

  const repoRoles = shuffle([
    'junior frontend developer with no cloud deployment experience',
    'senior platform/SRE engineer who knows Kubernetes well',
    'data scientist who needs to serve an ML model as an API',
    'startup founder who is non-technical and cost-sensitive',
    'backend engineer who has only ever deployed to Heroku or Railway',
    'game backend developer who needs low-latency APIs',
    'mobile app developer adding a server-side component',
    'DevOps engineer with existing Helm charts they want to keep using',
    'full-stack developer who already has a Dockerfile but has never used Kubernetes',
    'team lead who wants to reduce cloud costs with scale-to-zero',
  ]);

  const ideaRoles = shuffle([
    'junior developer with a weekend project idea and no existing code',
    'product manager who wants to prototype an idea without a dev team',
    'startup founder at the idea stage who needs to ship something fast',
    'student learning to build cloud apps for the first time',
    'freelancer who wants to build and host a client MVP quickly',
  ]);

  const repos = shuffle([
    'https://github.com/sabbour/ContosoAir',
    'https://github.com/Azure-Samples/aks-store-demo',
    'https://github.com/Azure-Samples/azure-voting-app-redis',
    'https://github.com/Azure-Samples/todo-nodejs-mongo-aks',
  ]);

  // ~half repo-based, ~half idea-based (at least 1 of each when count >= 2)
  const ideaCount  = Math.max(1, Math.floor(count / 2));
  const repoCount  = count - ideaCount;

  // Generate app ideas for idea-based personas in parallel
  const appIdeas = await Promise.all(Array.from({ length: ideaCount }, () => generateAppIdea(client)));
  process.stderr.write(`[Personas] App ideas: ${appIdeas.map(a => `"${a.slice(0, 60)}"`).join(', ')}\n`);

  const repoSlots  = repoRoles.slice(0, repoCount).map((r, i) =>
    `  Role: ${r} | Has repo: ${repos[i % repos.length]}`);
  const ideaSlots  = ideaRoles.slice(0, ideaCount).map((r, i) =>
    `  Role: ${r} | No repo — their app idea is: "${appIdeas[i]}"`);
  const allSlots   = shuffle([...repoSlots, ...ideaSlots])
    .map((s, i) => `${i + 1}. ${s}`).join('\n');

  const userPrompt = `Run ID: ${seed}. Generate exactly ${count} distinct user persona(s) for a cloud deployment assistant.

Each persona is assigned a role and context below — use them exactly:
${allSlots}

Return a JSON array with exactly ${count} object(s). Each object must have:
- "id": kebab-case slug derived from the name (e.g. "priya-ml", "dan-sre")
- "name": a realistic first name (vary gender and cultural background)
- "title": one-line description (name + role + key constraint, ≤ 60 chars)
- "opener": the very first chat message they send (1–2 sentences, natural).
  - If they HAVE a repo: mention the GitHub repo URL. Do NOT mention "AKS", "AKS Automatic", or "Kubernetes".
  - If they have NO repo: open with their app idea in their own words — they want to build it and get it live. Do NOT mention "AKS", "AKS Automatic", or "Kubernetes".
- "description": a 150–250 word system prompt defining who they are, what they want, their technical level, personality quirks, and how they react when things go wrong or are confusing. Do NOT mention "AKS Automatic" or "Kubernetes" as a goal. End with: "Keep responses SHORT — 1–3 sentences, like real chat messages."

Return ONLY the JSON array, no markdown fences, no extra text.`;

  const resp = await client.chat.completions.create({
    model: process.env.KICKSTART_CHAT_MODEL ?? 'gpt-5.4-mini',
    messages: [{ role: 'user', content: userPrompt }],
    max_completion_tokens: 400 * count,
    temperature: 1.0,
  });

  const raw = resp.choices[0]?.message?.content?.trim() ?? '[]';
  try {
    const parsed = JSON.parse(raw) as Persona[];
    process.stderr.write(`[Personas] Generated: ${parsed.map(p => `${p.name} (${p.title})`).join(', ')}\n\n`);
    return parsed;
  } catch {
    throw new Error(`Failed to parse generated personas:\n${raw}`);
  }
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ---------------------------------------------------------------------------
// Milestone detection (identical to run-sims.ts)
// ---------------------------------------------------------------------------

type MilestoneId = 'triage_routed'|'context_loaded'|'solution_shaped'|'artifacts_generated'|'repo_connected'|'pr_created';
interface Milestone { id: MilestoneId; label: string; elapsed_ms: number; turn: number; evidence: string; }

const MILESTONE_DEFS: {id: MilestoneId; label: string}[] = [
  { id: 'triage_routed',       label: 'Triage routed' },
  { id: 'context_loaded',      label: 'Context loaded' },
  { id: 'solution_shaped',     label: 'Solution shaped' },
  { id: 'artifacts_generated', label: 'Artifacts generated' },
  { id: 'repo_connected',      label: 'Repo connected' },
  { id: 'pr_created',          label: 'PR created' },
];

function detectMilestones(
  turn: number, elapsed_ms: number, agent: string,
  text: string, toolCalls: string[], a2ui: unknown[],
  prevAgent: string, achieved: Set<MilestoneId>,
): Milestone[] {
  const hit: Milestone[] = [];
  const tools = toolCalls.map(t => t.toLowerCase());
  const a2uiStr = JSON.stringify(a2ui).toLowerCase();
  const maybe = (id: MilestoneId, evidence: string) => {
    if (achieved.has(id)) return;
    achieved.add(id);
    hit.push({ id, label: MILESTONE_DEFS.find(m => m.id === id)!.label, elapsed_ms, turn, evidence });
  };

  // M1 triage_routed
  if (!achieved.has('triage_routed')) {
    const tf = tools.find(t => t.startsWith('transfer_to_') || t.includes('transfer'));
    if (tf) maybe('triage_routed', `tool: ${tf}`);
    else if (agent !== 'core.triage' && prevAgent === 'core.triage' && agent !== '?') maybe('triage_routed', `agent switch → ${agent}`);
  }
  // M2 context_loaded
  if (!achieved.has('context_loaded')) {
    if (tools.some(t => t.includes('inspect_repo') || t.includes('inspect'))) maybe('context_loaded', `tool: inspect_repo`);
    else if (a2uiStr.includes('"summarycard"') || a2uiStr.includes('"inspectcard"')) maybe('context_loaded', 'a2ui: SummaryCard');
    else if (/repo (scanned|analyzed|loaded|inspected)/i.test(text)) maybe('context_loaded', 'text: repo scanned');
  }
  // M3 solution_shaped
  if (!achieved.has('solution_shaped')) {
    const specAgents = ['aks.architect','aks.reviewer','azure.architect'];
    if (specAgents.includes(agent)) {
      if (tools.some(t => t.includes('show_card') || t.includes('emit_ui') || t.includes('show_form'))) maybe('solution_shaped', `agent ${agent} + UI card`);
      else if (/deployment plan|here.s (the|your) plan|I'll (set up|configure|generate|create)|let.s (set up|get|deploy)/i.test(text)) maybe('solution_shaped', 'text: plan signal');
    }
  }
  // M4 artifacts_generated
  if (!achieved.has('artifacts_generated')) {
    if (/^apiVersion:/m.test(text) || /^kind:\s+Deployment/m.test(text)) maybe('artifacts_generated', 'text: K8s manifest');
    else if (/```ya?ml[\s\S]*?apiVersion:/i.test(text)) maybe('artifacts_generated', 'text: yaml block');
    else if (/resource\s+\w+\s*'\w+'/i.test(text) && /\bparam\b/.test(text)) maybe('artifacts_generated', 'text: Bicep');
    else if (/^FROM\s+\w+/m.test(text) && /\bRUN\b/.test(text)) maybe('artifacts_generated', 'text: Dockerfile');
    else if (tools.some(t => t.includes('create_file') || t.includes('write_file') || t.includes('generate'))) maybe('artifacts_generated', 'tool: file create');
  }
  // M5 repo_connected
  if (!achieved.has('repo_connected')) {
    if (tools.some(t => t.includes('github_connect') || t.includes('git_push') || t.includes('install_app'))) maybe('repo_connected', 'tool: github');
    else if (/GitHub App (installed|connected)/i.test(text)) maybe('repo_connected', 'text: GitHub App');
    else if (/kubectl apply|helm (install|upgrade)|az deployment|azd (up|deploy)/i.test(text)) maybe('repo_connected', 'text: deploy cmd');
  }
  // M6 pr_created
  if (!achieved.has('pr_created')) {
    if (tools.some(t => t.includes('create_pr') || t.includes('create_pull'))) maybe('pr_created', 'tool: create_pr');
    else if (/pull request (opened|created)|PR (created|opened|#\d+)/i.test(text)) maybe('pr_created', 'text: PR created');
    else if (/github\.com\/[^/]+\/[^/]+\/pull\/\d+/i.test(text)) maybe('pr_created', 'text: PR URL');
    else if (/gh pr create\b/i.test(text)) maybe('pr_created', 'cmd: gh pr create');
    else if (/\bPR #\d+\b/i.test(text)) maybe('pr_created', 'text: PR number');
  }
  return hit;
}

// ---------------------------------------------------------------------------
// Persona LLM — generates the next user message given conversation history
// ---------------------------------------------------------------------------

interface ConvMessage { role: 'user' | 'assistant'; content: string; }

interface TurnRecord {
  turn:       number;
  elapsed_ms: number;
  userInput:  string;
  agent:      string;
  text:       string;
  toolCalls:  string[];
  a2ui:       unknown[];
  actions:    { index: number; event: string; optionId: string | null; label: string; agentInput: string }[];
  milestones: Milestone[];
  personaGenerated: boolean;
  frustration: number; // 0=happy … 5=ragequit
}

interface SimResult {
  persona:      Persona;
  turns:        TurnRecord[];
  milestones:   Milestone[];
  error?:       string;
  duration_ms:  number;
  goalMet:      boolean;
}

function buildPersonaClient(): OpenAI {
  const endpoint = process.env.AZURE_OPENAI_ENDPOINT;
  const apiKey   = process.env.AZURE_OPENAI_API_KEY;
  if (!endpoint || !apiKey) throw new Error('AZURE_OPENAI_ENDPOINT / AZURE_OPENAI_API_KEY not set');
  return new OpenAI({
    apiKey,
    baseURL: `${endpoint.replace(/\/$/, '')}/openai/deployments/${process.env.KICKSTART_CHAT_MODEL ?? 'gpt-5.4-mini'}`,
    defaultQuery: { 'api-version': '2024-12-01-preview' },
    defaultHeaders: { 'api-key': apiKey },
  });
}

async function generatePersonaResponse(
  client:   OpenAI,
  persona:  Persona,
  history:  ConvMessage[],
  lastAgentText: string,
  actions:  { event: string; optionId: string | null; label: string; agentInput: string }[],
): Promise<{ response: string; frustration: number }> {
  const actionsHint = actions.length > 0
    ? `\n\nAvailable actions you can select:\n${actions.map(a => `  - ${a.agentInput} → "${a.label}"`).join('\n')}\nIf you want to select one, respond with ONLY that action syntax (e.g. \`:select_inference:kaito\`). Otherwise respond normally.`
    : '';

  const systemPrompt = `${persona.description}

You are ${persona.name}. You came here because you want the system to do something for you, not to advise it.
You may be technically knowledgeable — but you are still the one asking for help, not giving it.
You understand what the assistant tells you, ask smart questions when something is unclear, and push back if something sounds wrong.
But you do NOT tell the assistant what architecture to use, which service to pick, or what the right answer is. That is their job, not yours.
React to what the assistant says. Answer their questions. If they ask for something you don't have, make something up or say you don't know.
NEVER repeat, rephrase, or echo what the assistant just said — always write a new, original response from your own perspective.
Keep responses SHORT — 1 to 3 sentences max, like real chat messages.

Respond with a JSON object (no markdown fences) with two fields:
- "response": your next chat message as ${persona.name}
- "frustration": integer 0–5 representing how frustrated ${persona.name} is RIGHT NOW
  0 = happy/cooperative, 1 = slightly uncertain, 2 = mildly confused or impatient,
  3 = noticeably frustrated, 4 = very frustrated / pushing back hard, 5 = about to give up`;

  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: 'system', content: systemPrompt },
    ...history,
    { role: 'assistant', content: lastAgentText + actionsHint },
    { role: 'user', content: `What does ${persona.name} say next? Reply with the JSON object only.` },
  ];

  const resp = await client.chat.completions.create({
    model:                 process.env.KICKSTART_CHAT_MODEL ?? 'gpt-5.4-mini',
    messages,
    max_completion_tokens: 160,
    temperature:           0.8,
  });
  const raw = resp.choices[0]?.message?.content?.trim() ?? '{}';
  try {
    const parsed = JSON.parse(raw) as { response?: string; frustration?: number };
    const response = (parsed.response ?? 'OK, continue.').trim();

    // Catch mirroring: if the persona is echoing the agent's text, replace with a frustrated pushback
    const similarity = longestCommonSubstring(response.toLowerCase(), lastAgentText.toLowerCase());
    const isMirroring = similarity / Math.max(response.length, 1) > 0.6;
    if (isMirroring) {
      return { response: "I'm not sure what you want from me here — can you just do this and show me the result?", frustration: 3 };
    }

    return {
      response,
      frustration: Math.min(5, Math.max(0, Math.round(parsed.frustration ?? 0))),
    };
  } catch {
    return { response: raw.slice(0, 200), frustration: 0 };
  }
}

function longestCommonSubstring(a: string, b: string): number {
  let max = 0;
  for (let i = 0; i < a.length; i++) {
    for (let j = 0; j < b.length; j++) {
      let len = 0;
      while (i + len < a.length && j + len < b.length && a[i + len] === b[j + len]) len++;
      if (len > max) max = len;
    }
  }
  return max;
}

// ---------------------------------------------------------------------------
// Run one persona through the probe
// ---------------------------------------------------------------------------

function fmtMs(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${Math.floor(ms / 60000)}m ${Math.round((ms % 60000) / 1000)}s`;
}

async function runPersona(persona: Persona, client: OpenAI): Promise<SimResult> {
  const start     = Date.now();
  const achieved  = new Set<MilestoneId>();
  const allMS:    Milestone[]  = [];
  const turns:    TurnRecord[] = [];
  const history:  ConvMessage[] = [];
  let prevAgent = 'core.triage';
  let error: string | undefined;

  const [cmd, ...cmdArgs] = PROBE_CMD.split(' ');
  const child = cp.spawn(cmd, cmdArgs, { env: { ...process.env }, stdio: ['pipe', 'pipe', 'pipe'] });

  child.stderr.on('data', (chunk: Buffer) => process.stderr.write(chunk));
  child.on('error', (err: Error) => { error = err.message; });

  let stdoutBuf = '';
  let turnNum   = 0;
  let pendingGeneration: Promise<{ response: string; frustration: number }> | null = null;
  let pendingFrustration = 0;

  // Send opener immediately
  const opener = persona.opener;
  process.stderr.write(`\n  ${'─'.repeat(72)}\n`);
  process.stderr.write(`  ${persona.name} 😊 (opener)\n`);
  for (const l of opener.split('\n')) process.stderr.write(`  👤  ${l}\n`);
  child.stdin.write(opener + '\n');

  await new Promise<void>((resolve) => {
    child.stdout.on('data', async (chunk: Buffer) => {
      stdoutBuf += chunk.toString('utf8');
      const lines = stdoutBuf.split('\n');
      stdoutBuf  = lines.pop() ?? '';

      for (const line of lines) {
        if (!line.trim()) continue;
        const elapsed_ms = Date.now() - start;
        let parsed: Record<string, unknown> = {};
        try { parsed = JSON.parse(line); } catch { /* non-JSON probe line */ }

        const agent     = (parsed.agent     as string)  ?? '?';
        const text      = (parsed.text      as string)  ?? line;
        const toolCalls = ((parsed.toolCalls as string[]) ?? []).filter(Boolean);
        const a2ui      = (parsed.a2ui      as unknown[]) ?? [];
        const actions   = (parsed.actions   as TurnRecord['actions']) ?? [];

        turnNum++;
        const newMS = detectMilestones(turnNum, elapsed_ms, agent, text, toolCalls, a2ui, prevAgent, achieved);
        allMS.push(...newMS);
        prevAgent = agent;

        const prevResult  = turnNum === 1 ? null : (await pendingGeneration ?? null);
        const userInput   = turnNum === 1 ? opener : (prevResult?.response ?? '');
        const frustration = turnNum === 1 ? 0 : (prevResult?.frustration ?? pendingFrustration);
        history.push({ role: 'user', content: userInput });
        history.push({ role: 'assistant', content: text });

        turns.push({
          turn: turnNum, elapsed_ms,
          userInput, agent, text, toolCalls, a2ui, actions,
          milestones: newMS,
          personaGenerated: turnNum > 1,
          frustration,
        });

        // Live console output — full conversation
        const frustEmoji = ['😊','😐','😕','😤','😡','🤬'][frustration] ?? '😐';
        const tools   = toolCalls.length ? ` [${toolCalls.join(', ')}]` : '';
        const divider = '─'.repeat(72);
        process.stderr.write(`\n  ${divider}\n`);
        process.stderr.write(`  T${String(turnNum).padStart(2)} ${fmtMs(elapsed_ms).padStart(6)}  •  ${agent}${tools}\n`);
        process.stderr.write(`  ${divider}\n`);
        // Full agent text, indented
        const agentLines = text.split('\n');
        for (const l of agentLines) process.stderr.write(`  🤖  ${l}\n`);
        newMS.forEach(m => process.stderr.write(`  ✅  [${m.label}] ${m.evidence}\n`));

        // Done?
        if (achieved.size >= 6 || turnNum >= MAX_TURNS) {
          child.stdin.end();
          return;
        }

        // Generate next persona response while the child awaits
        pendingGeneration = generatePersonaResponse(client, persona, history, text, actions)
          .then(result => {
            const fEmoji = ['😊','😐','😕','😤','😡','🤬'][result.frustration] ?? '😐';
            process.stderr.write(`\n  ${persona.name} ${fEmoji} (${result.frustration}/5)\n`);
            for (const l of result.response.split('\n')) process.stderr.write(`  👤  ${l}\n`);
            if (child.stdin.writable) child.stdin.write(result.response + '\n');
            pendingFrustration = result.frustration;
            return result;
          })
          .catch(err => {
            // Action-aware fallback: if buttons are available, click the most "proceed" one
            const proceedAction = actions.find(a =>
              /generate|proceed|looks right|confirm|yes|deploy|continue/i.test(a.label)
            ) ?? actions[0];
            const fallback = proceedAction ? proceedAction.agentInput : 'OK, please continue and generate everything needed.';
            process.stderr.write(`  ⚠️  LLM error: ${err.message} — fallback: ${fallback}\n`);
            if (child.stdin.writable) child.stdin.write(fallback + '\n');
            return { response: fallback, frustration: pendingFrustration };
          });
      }
    });
    child.on('close', () => resolve());
  });

  if (child.exitCode !== 0 && !error) error = `probe exited ${child.exitCode}`;
  const goalMet = achieved.size >= 6 && (allMS.at(-1)?.elapsed_ms ?? Infinity) <= GOAL_BUDGET_MS;
  return { persona, turns, milestones: allMS, error, duration_ms: Date.now() - start, goalMet };
}

// ---------------------------------------------------------------------------
// HTML generation
// ---------------------------------------------------------------------------

function frustrationBar(f: number): string {
  const pip  = (filled: boolean) => `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;margin:0 1px;background:${filled ? frustrationColor(f) : '#30363d'}"></span>`;
  return `<span title="Frustration ${f}/5" style="display:inline-flex;align-items:center;gap:1px">${[0,1,2,3,4].map(i => pip(i < f)).join('')}</span>`;
}
function frustrationColor(f: number): string {
  return ['#3fb950','#8bd450','#d29922','#f0883e','#f85149','#da3633'][f] ?? '#8b949e';
}
function frustrationEmoji(f: number): string {
  return ['😊','😐','😕','😤','😡','🤬'][f] ?? '😐';
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const AGENT_COLORS: Record<string, string> = {
  'core.triage':    '#58a6ff',
  'aks.architect':  '#3fb950',
  'aks.reviewer':   '#d29922',
  'azure.architect':'#a371f7',
  'azure.reviewer': '#f78166',
};
const agentColor = (a: string) => AGENT_COLORS[a] ?? '#8b949e';

const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;background:#0d1117;color:#e6edf3;line-height:1.6}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
code{font-family:'SF Mono',Consolas,monospace;font-size:12px;background:#161b22;border:1px solid #30363d;border-radius:4px;padding:1px 5px}
pre{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:12px 16px;overflow-x:auto;font-size:12px;margin:8px 0;white-space:pre-wrap;word-break:break-all}
.ph{background:#161b22;border-bottom:1px solid #21262d;padding:16px 32px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}
.ph h1{font-size:18px;font-weight:600}.back{font-size:13px;color:#8b949e;display:block;margin-bottom:4px}
.gb{margin-left:auto;padding:4px 14px;border-radius:12px;font-size:13px;font-weight:600}
.gm{background:#1a3a2a;color:#3fb950;border:1px solid #2ea043}.gnm{background:#3a1a1a;color:#f85149;border:1px solid #da3633}
.mb{display:flex;flex-wrap:wrap;gap:16px;align-items:flex-start;padding:20px 32px;border-bottom:1px solid #21262d}
.mst{display:flex;flex-direction:column;align-items:center;gap:3px;min-width:110px;text-align:center}
.md{width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:15px;font-weight:700}
.msd .md{background:#1a3a2a;color:#3fb950;border:2px solid #2ea043}.msp .md{background:#161b22;color:#6e7681;border:2px solid #30363d}
.ml{font-size:11px;font-weight:600}.mt{font-size:10px;color:#3fb950;font-family:monospace}.mev{font-size:9px;color:#6e7681;font-family:monospace;max-width:110px;word-break:break-all}
.bw{flex:1;min-width:200px;padding:0 8px;display:flex;flex-direction:column;gap:6px;justify-content:center}
.bl{font-size:11px;color:#8b949e;font-weight:600;text-transform:uppercase;letter-spacing:.05em}
.bt{height:8px;background:#21262d;border-radius:4px;position:relative;overflow:hidden}
.bf{height:100%;border-radius:4px}.bti{position:absolute;top:-2px;height:12px;width:2px;background:#6e7681;right:0}
.be{font-size:13px;font-weight:700;font-family:monospace}
.sm{padding:14px 32px;background:#161b22;border-bottom:1px solid #21262d}
.so{font-style:italic;color:#8b949e;font-size:14px;margin-top:4px}.ss{font-size:12px;color:#6e7681;margin-top:6px}
.eb{margin:16px 32px;padding:12px 16px;background:#3a1a1a;border:1px solid #da3633;border-radius:6px;color:#f85149;font-size:13px}
.turns{padding:24px 32px;display:flex;flex-direction:column;gap:20px;max-width:900px}
.turn{display:flex;flex-direction:column;gap:8px}
.tu{display:flex;flex-direction:column;align-items:flex-end;gap:2px}
.bu{background:#1c2128;border:1px solid #30363d;border-radius:12px 12px 4px 12px;padding:10px 14px;max-width:70%;font-size:14px;white-space:pre-wrap;word-break:break-word}
.bu-ai{background:#1a2438;border-color:#2055a4}
.tm{font-size:10px;color:#6e7681}
.ai-badge{font-size:9px;background:#1a2438;border:1px solid #2055a4;color:#58a6ff;border-radius:6px;padding:1px 6px;margin-bottom:2px;align-self:flex-end}
.ta{display:flex;flex-direction:column;gap:4px}
.al{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;margin-bottom:2px}
.tr{font-size:12px;color:#8b949e;display:flex;flex-wrap:wrap;gap:4px}
.ba{background:#161b22;border:1px solid #21262d;border-left-width:3px;border-radius:4px 12px 12px 12px;padding:12px 16px;font-size:14px;white-space:pre-wrap;word-break:break-word;max-width:85%}
.ar{display:flex;flex-wrap:wrap;gap:4px;margin-top:4px}
.ac{font-family:monospace;font-size:11px;background:#1a1a2e;border:1px solid #30363d;border-radius:10px;padding:2px 8px;color:#c084fc}
.msb{align-self:flex-start;background:#1a3a2a;border:1px solid #2ea043;border-radius:6px;padding:3px 10px;font-size:12px;color:#3fb950}
.msbe{color:#6e7681;font-family:monospace;font-size:10px;margin-left:6px}
.f-badge{align-self:flex-end;font-size:11px;border:1px solid;border-radius:6px;padding:2px 7px;display:inline-flex;align-items:center;gap:5px;margin-top:2px}
grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px;padding:24px 32px}
.sc{background:#161b22;border:1px solid #21262d;border-radius:8px;padding:16px;display:flex;flex-direction:column;gap:10px}
.sc:hover{border-color:#58a6ff}.sct{font-size:15px;font-weight:600}.sci{font-size:11px;color:#6e7681;font-family:monospace}
.scm{display:flex;gap:4px;flex-wrap:wrap}.scm span{font-size:10px;padding:1px 6px;border-radius:8px}
.mh{background:#1a3a2a;color:#3fb950;border:1px solid #2ea043}.mm{background:#21262d;color:#6e7681;border:1px solid #30363d}
.sct2{font-size:12px;color:#8b949e}.ii{padding:16px 32px;color:#8b949e;font-size:14px;border-bottom:1px solid #21262d}
`;

function bar(milestones: Milestone[], totalMs: number): string {
  const ach   = new Set(milestones.map(m => m.id));
  const pct   = Math.min(100, (totalMs / GOAL_BUDGET_MS) * 100);
  const col   = totalMs <= GOAL_BUDGET_MS ? '#3fb950' : '#f85149';
  const steps = MILESTONE_DEFS.map(def => {
    const hit  = milestones.find(m => m.id === def.id);
    const done = ach.has(def.id);
    return `<div class="mst ${done ? 'msd' : 'msp'}"><div class="md">${done ? '&#10003;' : ''}</div><div class="ml">${esc(def.label)}</div>${hit ? `<div class="mt">${fmtMs(hit.elapsed_ms)}</div><div class="mev">${esc(hit.evidence)}</div>` : ''}</div>`;
  }).join('');
  return `<div class="mb">${steps}<div class="bw"><div class="bl">Time vs 5-min goal</div><div class="bt"><div class="bf" style="width:${pct.toFixed(1)}%;background:${col}"></div><div class="bti"></div></div><div class="be" style="color:${col}">${fmtMs(totalMs)} / 5:00</div></div></div>`;
}

function renderTurn(t: TurnRecord): string {
  const col     = agentColor(t.agent);
  const msb     = t.milestones.map(m => `<div class="msb">&#127937; ${esc(m.label)}<span class="msbe">${esc(m.evidence)}</span></div>`).join('');
  const th      = t.toolCalls.length ? `<div class="tr">&#128295; ${t.toolCalls.map(tc => `<code>${esc(tc)}</code>`).join(' ')}</div>` : '';
  const ah      = t.actions.length ? `<div class="ar">${t.actions.map(a => `<span class="ac">${esc(a.agentInput)}</span>`).join('')}</div>` : '';
  const txh     = t.text.includes('\n') ? `<pre>${esc(t.text)}</pre>` : esc(t.text);
  const aiBadge = t.personaGenerated ? `<div class="ai-badge">&#129302; AI persona</div>` : '';
  const fColor  = frustrationColor(t.frustration);
  const fLabel  = t.personaGenerated
    ? `<div class="f-badge" style="color:${fColor};border-color:${fColor}" title="Frustration ${t.frustration}/5">${frustrationEmoji(t.frustration)} ${frustrationBar(t.frustration)}</div>`
    : '';
  return `<div class="turn">
    <div class="tu">${aiBadge}<div class="bu${t.personaGenerated ? ' bu-ai' : ''}" style="${t.personaGenerated ? `border-left:3px solid ${fColor}` : ''}">${esc(t.userInput)}</div>${fLabel}<div class="tm">T${t.turn} &mdash; ${fmtMs(t.elapsed_ms)}</div></div>
    ${msb}
    <div class="ta"><div class="al" style="color:${col}">&#9679; ${esc(t.agent)}</div>${th}<div class="ba" style="border-left-color:${col}">${txh}</div>${ah}</div>
  </div>`;
}

function frustrationSparkline(turns: TurnRecord[]): string {
  const generated = turns.filter(t => t.personaGenerated);
  if (!generated.length) return '';
  const max = 5;
  const h   = 32;
  const w   = Math.max(generated.length * 12, 60);
  const pts = generated.map((t, i) => {
    const x = (i / Math.max(generated.length - 1, 1)) * (w - 4) + 2;
    const y = h - 2 - ((t.frustration / max) * (h - 4));
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(' ');
  const avg = generated.reduce((s, t) => s + t.frustration, 0) / generated.length;
  const avgColor = frustrationColor(Math.round(avg));
  return `<div style="display:flex;align-items:center;gap:10px;margin-top:8px">
    <span style="font-size:11px;color:#8b949e;font-weight:600;text-transform:uppercase;letter-spacing:.05em">Frustration</span>
    <svg width="${w}" height="${h}" style="overflow:visible">
      <polyline points="${pts}" fill="none" stroke="${avgColor}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>
      ${generated.map((t, i) => {
        const x = (i / Math.max(generated.length - 1, 1)) * (w - 4) + 2;
        const y = h - 2 - ((t.frustration / max) * (h - 4));
        return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="3" fill="${frustrationColor(t.frustration)}" title="T${t.turn}: ${t.frustration}/5"/>`;
      }).join('')}
    </svg>
    <span style="font-size:12px;font-weight:700;color:${avgColor}">${frustrationEmoji(Math.round(avg))} avg ${avg.toFixed(1)}/5</span>
  </div>`;
}

function simPage(r: SimResult): string {
  const ach = new Set(r.milestones.map(m => m.id));
  const ts  = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(r.persona.id)}: ${esc(r.persona.title)}</title><style>${CSS}</style></head><body>
<div class="ph"><div><a class="back" href="index.html">&larr; All personas</a><h1>&#129302; ${esc(r.persona.title)}</h1></div>
<span style="color:#6e7681;font-size:12px">${ts}</span><div class="gb ${r.goalMet ? 'gm' : 'gnm'}">${r.goalMet ? '&#9989; Goal met' : '&#10060; Not met'}</div></div>
${bar(r.milestones, r.duration_ms)}
<div class="sm"><div class="so">&ldquo;${esc(r.persona.opener)}&rdquo;</div>
<div class="ss">${r.turns.length} turns &middot; ${fmtMs(r.duration_ms)} &middot; ${ach.size}/6 milestones &middot; <span style="color:#58a6ff">&#129302; AI-driven responses</span></div>
${frustrationSparkline(r.turns)}</div>
${r.error ? `<div class="eb">&#9888; ${esc(r.error)}</div>` : ''}
<div class="turns">${r.turns.map(renderTurn).join('\n')}</div></body></html>`;
}

function indexPage(results: SimResult[]): string {
  const ts    = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const cards = results.map(r => {
    const ach    = new Set(r.milestones.map(m => m.id));
    const badges = MILESTONE_DEFS.map(d => `<span class="${ach.has(d.id) ? 'mh' : 'mm'}">${d.label}</span>`).join('');
    return `<a class="sc" href="${esc(r.persona.id)}.html"><div class="sci">${esc(r.persona.id)} &middot; &#129302; AI persona</div>
<div class="sct">${esc(r.persona.title)}</div><div class="scm">${badges}</div>
<div class="sct2">${ach.size}/6 &middot; ${fmtMs(r.duration_ms)} &middot; <strong style="color:${r.goalMet ? '#3fb950' : '#f85149'}">${r.goalMet ? '&#9989; Met' : '&#10060; Not met'}</strong></div></a>`;
  }).join('');
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Persona Sim Report</title><style>${CSS}</style></head><body>
<div class="ph"><h1>&#127919; Deploy to AKS Automatic &mdash; AI Persona Sims</h1>
<span style="color:#8b949e;font-size:13px">${ts} &middot; goal: 5 min &middot; &#129302; AI-driven personas</span></div>
<div class="ii">Each card links to the full conversation. User responses were generated by an LLM adopting the persona — pushing back when frustrated, picking actions, driving toward deployment.</div>
<div class="ig">${cards}</div></body></html>`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const count  = parseInt(args.count ?? '3', 10);
  const client = buildPersonaClient();

  const personas = await generatePersonas(client, count);
  if (!personas.length) { process.stderr.write('No personas generated\n'); process.exit(1); }

  fs.mkdirSync(REPORTS_DIR, { recursive: true });

  process.stderr.write(`\n[Goal] Deploy to AKS Automatic in < 5 minutes\n`);
  process.stderr.write(`[Mode] AI-driven personas (LLM generates each response)\n`);
  process.stderr.write(`[Max ] ${MAX_TURNS} turns per persona\n`);
  process.stderr.write(`Running ${personas.length} persona(s)...\n\n`);

  const results: SimResult[] = [];

  for (const persona of personas) {
    process.stderr.write(`  ${persona.id}: ${persona.title}\n  ${'─'.repeat(60)}\n`);
    const result = await runPersona(persona, client);
    results.push(result);
    process.stderr.write(`\n  ${result.goalMet ? '[GOAL MET]' : '[NOT MET]'} ${result.milestones.length}/6 milestones in ${fmtMs(result.duration_ms)}\n`);

    const outFile = path.join(REPORTS_DIR, `${persona.id}.html`);
    fs.writeFileSync(outFile, simPage(result), 'utf8');
    process.stderr.write(`  -> ${outFile}\n\n`);

    fs.writeFileSync(path.join(REPORTS_DIR, 'index.html'), indexPage(results), 'utf8');
  }

  process.stderr.write(`All done -> ${path.join(REPORTS_DIR, 'index.html')}\n`);
}

main().catch((e: unknown) => { process.stderr.write(`Fatal: ${e}\n`); process.exit(1); });
