// Generated by squad init/upgrade — do not edit
//
// Standalone token resolution for agent identity.
// Uses only Node.js built-in modules — no npm dependencies required.
//
// Usage:
//   node .squad/scripts/resolve-token.mjs <role_slug>
//   node .squad/scripts/resolve-token.mjs --required <role_slug>
// Output: installation access token on stdout. In default mode, failures print nothing and exit 0.
// In --required mode, failures print a reason to stderr and exit 1.

import { createSign } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';

// ============================================================================
// Base64url helpers
// ============================================================================

function base64url(input) {
  const b64 = Buffer.from(input).toString('base64');
  return b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// ============================================================================
// Credential loading (inline from storage.ts)
// ============================================================================

/**
 * Load an app registration from `.squad/identity/apps/{key}.json`.
 * @param {string} projectRoot
 * @param {string} key
 * @returns {{ appId: number, appSlug: string, installationId: number } | null}
 */
function loadAppRegistration(projectRoot, key) {
  const regPath = join(projectRoot, '.squad', 'identity', 'apps', `${key}.json`);
  try {
    const raw = readFileSync(regPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * Load the identity config from `.squad/identity/config.json`.
 * @param {string} projectRoot
 * @returns {{ tier?: string, apps?: Record<string, { roleSlug?: string }> } | null}
 */
function loadIdentityConfig(projectRoot) {
  const configPath = join(projectRoot, '.squad', 'identity', 'config.json');
  try {
    const raw = readFileSync(configPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

const ROLE_ALIASES = {
  lead: ['lead', 'leela', 'architect', 'architecture', 'coordinator', 'squad', 'zapp', 'nibbler', 'ralph'],
  backend: ['backend', 'bender', 'core', 'core-dev', 'backend-dev'],
  frontend: ['frontend', 'fry', 'ui', 'frontend-dev'],
  tester: ['tester', 'hermes', 'qa', 'test', 'observability'],
  scribe: ['scribe'],
};

/**
 * Normalize a role-like string into a lowercase slug.
 * @param {string} roleKey
 * @returns {string | null}
 */
function normalizeRoleKey(roleKey) {
  if (typeof roleKey !== 'string') return null;
  const normalized = roleKey.trim().toLowerCase().replace(/[\s_]+/g, '-');
  return normalized || null;
}

/**
 * Resolve a requested role to the configured identity role slug.
 * Uses only explicit config keys or explicit alias mappings.
 * @param {string} projectRoot
 * @param {string} roleKey
 * @returns {string | null}
 */
function resolveRoleSlug(projectRoot, roleKey) {
  const config = loadIdentityConfig(projectRoot);
  const normalized = normalizeRoleKey(roleKey);
  if (!config?.apps || !normalized) return normalized;

  if (config.tier === 'shared') {
    return config.apps.shared ? 'shared' : null;
  }

  if (config.apps[normalized]) {
    return normalized;
  }

  for (const [resolvedRole, aliases] of Object.entries(ROLE_ALIASES)) {
    if (aliases.includes(normalized)) {
      if (config.apps[resolvedRole]) {
        return resolvedRole;
      }
      break;
    }
  }

  return null;
}

// ============================================================================
// JWT generation
// ============================================================================

/**
 * Generate a JWT for GitHub App authentication (RS256, 9 min TTL).
 * @param {number} appId
 * @param {string} privateKeyPem
 * @returns {string}
 */
function generateAppJWT(appId, privateKeyPem) {
  const now = Math.floor(Date.now() / 1000);
  const header = { alg: 'RS256', typ: 'JWT' };
  const payload = {
    iss: appId,
    iat: now - 60,
    exp: now + 540,
  };

  const encodedHeader = base64url(JSON.stringify(header));
  const encodedPayload = base64url(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const signer = createSign('RSA-SHA256');
  signer.update(signingInput);
  signer.end();
  const signature = signer.sign(privateKeyPem);
  const encodedSignature = base64url(signature);

  return `${signingInput}.${encodedSignature}`;
}

// ============================================================================
// Installation token exchange
// ============================================================================

/**
 * Exchange a JWT for an installation access token via GitHub API.
 * @param {string} jwt
 * @param {number} installationId
 * @returns {Promise<{ token: string, expiresAt: Date }>}
 */
async function getInstallationToken(jwt, installationId) {
  const url = `https://api.github.com/app/installations/${installationId}/access_tokens`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${jwt}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(
      `GitHub API error ${response.status} creating installation token: ${body}`,
    );
  }

  const data = await response.json();
  return {
    token: data.token,
    expiresAt: new Date(data.expires_at),
  };
}

// ============================================================================
// Environment variable credential resolution
// ============================================================================

/**
 * Resolve credentials from env vars: SQUAD_{ROLE}_APP_ID, _PRIVATE_KEY, _INSTALLATION_ID.
 * PEM may be base64-encoded; decoded automatically when it doesn't start with "-----BEGIN".
 * @param {string} roleKey
 * @returns {{ appId: number, pem: string, installationId: number } | null}
 */
function resolveEnvCredentials(roleKey) {
  const envKey = roleKey.toUpperCase();
  const appIdStr = process.env[`SQUAD_${envKey}_APP_ID`];
  const pemRaw = process.env[`SQUAD_${envKey}_PRIVATE_KEY`];
  const installIdStr = process.env[`SQUAD_${envKey}_INSTALLATION_ID`];

  if (!appIdStr || !pemRaw || !installIdStr) return null;

  const appId = Number(appIdStr);
  const installationId = Number(installIdStr);
  if (!Number.isFinite(appId) || !Number.isFinite(installationId)) return null;

  const pem = pemRaw.trimStart().startsWith('-----BEGIN')
    ? pemRaw
    : Buffer.from(pemRaw, 'base64').toString('utf-8');

  return { appId, pem, installationId };
}

// ============================================================================
// Token cache (in-process, keyed by roleKey)
// ============================================================================

const tokenCache = new Map();
const REFRESH_MARGIN_MS = 10 * 60 * 1000; // 10 minutes

function clearTokenCache() {
  tokenCache.clear();
}

// ============================================================================
// High-level token resolution
// ============================================================================

/**
 * Resolve an installation access token for the given role.
 *
 * Resolution order:
 *   1. Cache (if still valid)
 *   2. Environment variables (SQUAD_{ROLE}_APP_ID / PRIVATE_KEY / INSTALLATION_ID)
 *   3. Filesystem (.squad/identity/)
 *
 * @param {string} projectRoot - Project root directory (parent of .squad/)
 * @param {string} roleKey - Role key (e.g. 'lead', 'backend', 'shared')
 * @returns {Promise<string | null>}
 */
async function resolveTokenWithDiagnostics(projectRoot, roleKey) {
  const normalizedRoleKey = normalizeRoleKey(roleKey);
  try {
    const resolvedRoleKey = resolveRoleSlug(projectRoot, roleKey);
    if (!resolvedRoleKey) {
      return {
        token: null,
        error: `No GitHub App mapping configured for role "${normalizedRoleKey ?? String(roleKey)}".`,
      };
    }

    // Check cache
    const cached = tokenCache.get(resolvedRoleKey);
    if (cached) {
      const remainingMs = cached.expiresAt.getTime() - Date.now();
      if (remainingMs > REFRESH_MARGIN_MS) {
        return { token: cached.token, error: null };
      }
      tokenCache.delete(resolvedRoleKey);
    }

    // Path 1: Environment variables (CI/CD override)
    const envCreds = resolveEnvCredentials(resolvedRoleKey);
    if (envCreds) {
      const jwt = generateAppJWT(envCreds.appId, envCreds.pem);
      const { token, expiresAt } = await getInstallationToken(jwt, envCreds.installationId);
      tokenCache.set(resolvedRoleKey, { token, expiresAt });
      return { token, error: null };
    }

    // Path 2: Filesystem (default)
    const reg = loadAppRegistration(projectRoot, resolvedRoleKey);
    if (!reg) {
      return {
        token: null,
        error: `No GitHub App registration found for role "${resolvedRoleKey}".`,
      };
    }

    const pemPath = join(projectRoot, '.squad', 'identity', 'keys', `${resolvedRoleKey}.pem`);
    if (!existsSync(pemPath)) {
      return {
        token: null,
        error: `No GitHub App private key found for role "${resolvedRoleKey}".`,
      };
    }

    const pem = readFileSync(pemPath, 'utf-8');
    const jwt = generateAppJWT(reg.appId, pem);
    const { token, expiresAt } = await getInstallationToken(jwt, reg.installationId);

    tokenCache.set(resolvedRoleKey, { token, expiresAt });
    return { token, error: null };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      token: null,
      error: message || `Failed to resolve GitHub App token for role "${normalizedRoleKey ?? String(roleKey)}".`,
    };
  }
}

async function resolveToken(projectRoot, roleKey) {
  const { token } = await resolveTokenWithDiagnostics(projectRoot, roleKey);
  return token;
}

export { clearTokenCache, resolveRoleSlug, resolveToken, resolveTokenWithDiagnostics };

// ============================================================================
// CLI entry point
// ============================================================================

const isCliInvocation =
  typeof process.argv[1] === 'string' &&
  resolvePath(process.argv[1]) === fileURLToPath(import.meta.url);

if (isCliInvocation) {
  const args = process.argv.slice(2);
  const required = args[0] === '--required';
  const roleSlug = required ? args[1] : args[0];
  if (!roleSlug) {
    process.exit(0);
  }

  // Derive project root from script location (.squad/scripts/ → repo root).
  // Agents invoke this via absolute path so process.cwd() may be a worktree.
  let projectRoot = process.cwd();
  try {
    const scriptDir = dirname(fileURLToPath(import.meta.url));
    projectRoot = join(scriptDir, '..', '..');
  } catch {
    // Fallback to cwd if import.meta.url is unavailable
  }

  const { token, error } = await resolveTokenWithDiagnostics(projectRoot, roleSlug);
  if (token) {
    process.stdout.write(token);
  } else if (required) {
    if (error) {
      process.stderr.write(`${error}\n`);
    }
    process.exit(1);
  }
}
