/**
 * @module @kickstart/api/lib/session-store
 *
 * In-memory session store with TTL cleanup.
 * Stores conversation state for the web surface API.
 */

import { randomUUID } from "node:crypto";
import {
  Phase,
  createInitialState,
  buildSystemPrompt,
} from "@kickstart/core";
import type {
  SessionState,
  ConversationState,
  ConversationMessage,
} from "@kickstart/core";

/** Metadata for a file generated by the LLM, tracked across turns.
 *  Stores only what's needed for summaries — never full file content. */
export interface GeneratedArtifact {
  filename: string;
  language: string;
  /** Bicep resource declarations, e.g. ["myCluster (Microsoft.ContainerService/managedClusters)"] */
  bicepResources: string[];
  /** K8s resource declarations, e.g. ["Deployment: my-app"] */
  k8sResources: string[];
}

/** Session wrapper with engine state and TTL tracking. */
export interface ApiSession {
  state: SessionState;
  engineState: ConversationState;
  lastAccessed: number;
  /** Tracks files generated by the LLM across turns for artifact summary. */
  generatedArtifacts: GeneratedArtifact[];
}

const sessions = new Map<string, ApiSession>();

/** Session TTL: 1 hour. */
const SESSION_TTL_MS = 60 * 60 * 1000;

/** Purge stale sessions every 10 minutes. */
const cleanupInterval = setInterval(() => {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (now - session.lastAccessed > SESSION_TTL_MS) {
      sessions.delete(id);
    }
  }
}, 10 * 60 * 1000);
cleanupInterval.unref();

/** Retrieve an existing session, refreshing its TTL. */
export function getSession(sessionId: string): ApiSession | undefined {
  const session = sessions.get(sessionId);
  if (session) session.lastAccessed = Date.now();
  return session;
}

/** Create a new session with Discover-phase system prompt. */
export function createSession(): ApiSession {
  const sessionId = randomUUID();
  const now = new Date().toISOString();
  const engineState = createInitialState();

  const systemPrompt = buildSystemPrompt({
    phase: Phase.Discover,
    appDefinition: {},
  });

  const session: ApiSession = {
    state: {
      sessionId,
      currentPhase: Phase.Discover,
      createdAt: now,
      updatedAt: now,
      appDefinition: {},
      messages: [
        { role: "system", content: systemPrompt, timestamp: now },
      ],
    },
    engineState,
    lastAccessed: Date.now(),
    generatedArtifacts: [],
  };

  sessions.set(sessionId, session);
  return session;
}

/**
 * Client-provided message for session hydration.
 * Only role + content — the server never trusts client timestamps or system prompts.
 */
export interface ClientMessage {
  role: "user" | "assistant";
  content: string;
}

/** Client-provided artifact metadata for session rehydration.
 *  Validated/sanitized on ingress — only metadata, never file content. */
export interface ClientArtifact {
  filename: string;
  language: string;
  bicepResources?: string[];
  k8sResources?: string[];
}

/**
 * Create a new session and seed it with client-provided conversation history.
 * Used when the in-memory session has been lost (cold start / scale event)
 * but the client still holds the message history in React state.
 *
 * System messages are always rebuilt server-side — client-sent system
 * messages are silently dropped.
 *
 * If `clientArtifacts` is provided, the session's generatedArtifacts are
 * populated directly from it instead of trying to parse assistant message JSON.
 */
export function hydrateSession(
  clientMessages: ClientMessage[],
  clientArtifacts?: ClientArtifact[],
): ApiSession {
  const session = createSession();
  const now = new Date().toISOString();

  for (const msg of clientMessages) {
    // Only allow user/assistant — never trust client-sent system prompts
    if (msg.role !== "user" && msg.role !== "assistant") continue;
    if (!msg.content) continue;

    session.state.messages.push({
      role: msg.role,
      content: msg.content,
      timestamp: now,
    });
  }

  // Restore artifact tracking from client-provided metadata (preferred),
  // falling back to parsing assistant messages (legacy, rarely succeeds).
  if (clientArtifacts?.length) {
    session.generatedArtifacts = sanitizeClientArtifacts(clientArtifacts);
  } else {
    for (const msg of clientMessages) {
      if (msg.role === "assistant" && msg.content) {
        rebuildArtifactsFromMessage(msg.content, session.generatedArtifacts);
      }
    }
  }

  session.state.updatedAt = now;
  return session;
}

/** Max length for a single artifact filename from client. */
const MAX_FILENAME_LENGTH = 256;
/** Max combined resource entries per artifact from client. */
const MAX_RESOURCES_PER_ARTIFACT = 20;

/** Sanitize and cap client-provided artifact metadata. */
function sanitizeClientArtifacts(raw: ClientArtifact[]): GeneratedArtifact[] {
  const seen = new Set<string>();
  const result: GeneratedArtifact[] = [];

  for (const a of raw) {
    if (result.length >= MAX_TRACKED_ARTIFACTS) break;
    if (typeof a.filename !== "string" || !a.filename.trim()) continue;

    const filename = a.filename.trim().slice(0, MAX_FILENAME_LENGTH);
    if (seen.has(filename)) continue;
    seen.add(filename);

    const language = typeof a.language === "string" && a.language.trim()
      ? a.language.trim()
      : inferLanguage(filename);
    const bicepResources = sanitizeResourceList(a.bicepResources);
    const k8sResources = sanitizeResourceList(a.k8sResources);

    result.push({
      filename,
      language,
      bicepResources: bicepResources.slice(0, MAX_RESOURCES_PER_ARTIFACT),
      k8sResources: k8sResources.slice(0, MAX_RESOURCES_PER_ARTIFACT),
    });
  }

  return result;
}

/** Validate a resource list — keep only non-empty strings. */
function sanitizeResourceList(list: unknown): string[] {
  if (!Array.isArray(list)) return [];
  return list
    .filter((s): s is string => typeof s === "string" && s.trim().length > 0)
    .map((s) => s.trim().slice(0, 200));
}

/**
 * Build a human-readable summary of generated artifacts for injection into the
 * system prompt. Returns empty string if no artifacts exist.
 */
export function buildArtifactSummary(artifacts: GeneratedArtifact[]): string {
  if (!artifacts.length) return "";

  const lines: string[] = ["## Previously generated files"];
  for (const a of artifacts) {
    let line = `- ${a.filename} (${a.language})`;
    if (a.bicepResources.length > 0) {
      line += ` — Bicep resources: ${a.bicepResources.join(", ")}`;
    }
    if (a.k8sResources.length > 0) {
      line += ` — K8s resources: ${a.k8sResources.join(", ")}`;
    }
    lines.push(line);
  }
  return lines.join("\n");
}

/** Max number of artifacts tracked to prevent unbounded growth. */
export const MAX_TRACKED_ARTIFACTS = 50;

/** Infer language from filename extension. */
export function inferLanguage(filename: string): string {
  const ext = filename.split(".").pop() ?? "";
  const langMap: Record<string, string> = {
    ts: "typescript", js: "javascript", py: "python", go: "go",
    rs: "rust", java: "java", cs: "csharp", bicep: "bicep",
    yaml: "yaml", yml: "yaml", json: "json", md: "markdown",
    dockerfile: "dockerfile", sh: "shell",
  };
  return langMap[ext.toLowerCase()] ?? ext;
}

/** Extract metadata from file content at upsert time — never stores the content. */
export function extractArtifactMetadata(
  filename: string,
  language: string,
  content: string,
): GeneratedArtifact {
  const bicepResources: string[] = [];
  const k8sResources: string[] = [];

  if (filename.endsWith(".bicep")) {
    const re = /resource\s+(\w+)\s+'(Microsoft\.[^'@]+)@/g;
    let m;
    while ((m = re.exec(content)) !== null) {
      bicepResources.push(`${m[1]} (${m[2]})`);
    }
  }

  if (filename.endsWith(".yaml") || filename.endsWith(".yml")) {
    const docs = content.split(/^---$/m);
    for (const doc of docs) {
      const kindMatch = doc.match(/kind:\s*(\w+)/);
      const nameMatch = doc.match(/name:\s*["']?([a-z0-9][-a-z0-9]*)["']?/m);
      if (kindMatch) {
        k8sResources.push(kindMatch[1] + (nameMatch ? ": " + nameMatch[1] : ""));
      }
    }
  }

  return { filename, language: language || inferLanguage(filename), bicepResources, k8sResources };
}

/** Upsert an artifact into the list — keep the most recent entries, capped at MAX_TRACKED_ARTIFACTS. */
export function upsertArtifact(list: GeneratedArtifact[], artifact: GeneratedArtifact): void {
  const idx = list.findIndex((a) => a.filename === artifact.filename);

  if (idx >= 0) {
    list.splice(idx, 1);
  } else if (list.length >= MAX_TRACKED_ARTIFACTS) {
    list.shift();
  }

  list.push(artifact);
}

/**
 * Extract FileEditor metadata from A2UI updateComponents messages.
 * Used both during a live turn (converse.ts) and when rebuilding
 * artifacts during session hydration.
 */
export function extractArtifactsFromA2UI(
  a2uiMessages: Array<{ updateComponents?: { components: unknown[] } }>,
): GeneratedArtifact[] {
  const artifacts: GeneratedArtifact[] = [];
  for (const msg of a2uiMessages) {
    if (!msg.updateComponents?.components) continue;
    for (const comp of msg.updateComponents.components) {
      const c = comp as Record<string, unknown>;
      if (c.component === "FileEditor" && typeof c.filename === "string") {
        const artifact = extractArtifactMetadata(
          c.filename,
          typeof c.language === "string" ? c.language : "",
          typeof c.content === "string" ? c.content : "",
        );
        artifacts.push(artifact);
      }
    }
  }
  return artifacts;
}

/**
 * Scan a message (raw JSON or A2UI content) for FileEditor components
 * and upsert any found artifacts into the list.
 */
function rebuildArtifactsFromMessage(
  content: string,
  artifacts: GeneratedArtifact[],
): void {
  // Match FileEditor components in assistant messages — these appear in
  // A2UI updateComponents payloads as JSON objects with component:"FileEditor"
  const fileEditorPattern = /"component"\s*:\s*"FileEditor"/;
  if (!fileEditorPattern.test(content)) return;

  try {
    const parsed = JSON.parse(content) as Record<string, unknown>;
    const a2ui = parsed.a2ui as Array<{ updateComponents?: { components: unknown[] } }> | undefined;
    if (!Array.isArray(a2ui)) return;

    for (const artifact of extractArtifactsFromA2UI(a2ui)) {
      upsertArtifact(artifacts, artifact);
    }
  } catch {
    // Content isn't valid JSON — skip silently
  }
}

/** Append a message to the session's history. */
export function addMessage(
  sessionId: string,
  role: ConversationMessage["role"],
  content: string,
): void {
  const session = sessions.get(sessionId);
  if (!session) return;
  session.state.messages.push({
    role,
    content,
    timestamp: new Date().toISOString(),
  });
  session.state.updatedAt = new Date().toISOString();
  session.lastAccessed = Date.now();
}
