/**
 * @module @aks-kickstart/api/lib/session-store
 *
 * In-memory session store with TTL cleanup.
 * Stores conversation state for the web surface API.
 */

import { randomUUID } from "node:crypto";
import {
  Phase,
  SETUP_GENERATION_STEP_ORDER,
  buildSystemPrompt,
} from "@aks-kickstart/harness";
import type {
  SessionState,
  ConversationMessage,
  CostEstimateProps,
  SetupGenerationRunState,
  SetupGenerationSnapshot,
} from "@aks-kickstart/harness";
import {
  cloneSetupGenerationRun,
  isValidSetupGenerationSnapshot,
} from "./setup-generation-state.js";
import { buildUsageSummary } from "./usage-tracking.js";
import type { TurnUsage, UsageSummary } from "./usage-tracking.js";

/** Metadata for a file generated by the LLM, tracked across turns.
 *  Stores only what's needed for summaries — never full file content. */
export interface GeneratedArtifact {
  filename: string;
  language: string;
  /** Bicep resource declarations, e.g. ["myCluster (Microsoft.ContainerService/managedClusters)"] */
  bicepResources: string[];
  /** K8s resource declarations, e.g. ["Deployment: my-app"] */
  k8sResources: string[];
}

export interface DeployCostGateState {
  acknowledgedAt: string;
  estimatedMonthlyTotal: number;
  currency: string;
  source: string;
}

export interface DeployErrorState {
  code: string;
  message: string;
  actionableSteps?: string[];
  retryable?: boolean;
}

export type DeployStage = "idle" | "cost-gated" | "target-selected" | "deploying" | "succeeded" | "failed";

export interface DeployState {
  stage: DeployStage;
  updatedAt: string;
  costGate?: DeployCostGateState;
  activeRunId?: string;
  deploymentName?: string;
  appUrl?: string;
  lastError?: DeployErrorState;
}

export interface CostEstimateCacheEntry {
  value: CostEstimateProps;
  source: "live" | "estimated";
  cachedAt: string;
  expiresAt: number;
}

/** Session wrapper with engine state and TTL tracking. */
export interface ApiSession {
  state: SessionState;
  lastAccessed: number;
  /** Tracks files generated by the LLM across turns for artifact summary. */
  generatedArtifacts: GeneratedArtifact[];
  /** Token usage captured for assistant turns in this session. */
  usageHistory: TurnUsage[];
  /** SWA principal that owns this session. */
  principalId?: string;
  /** Only server-owned phase state may escalate routing to codex. */
  routingPhaseTrusted: boolean;
  /** Server-validated setup generation state for stepwise file generation. */
  setupGenerationRun?: SetupGenerationRunState;
  /** Client-supplied setup generation snapshots are trusted only after validation. */
  setupGenerationTrusted: boolean;
  /** Thin deployment state for the real Azure happy path. */
  deployState: DeployState;
  /** Per-session CostEstimate pricing cache keyed by normalized pricing request. */
  costEstimateCache: Map<string, CostEstimateCacheEntry>;
}

const sessions = new Map<string, ApiSession>();

/** Session TTL: 1 hour. */
const SESSION_TTL_MS = 60 * 60 * 1000;

/** Purge stale sessions every 10 minutes. */
const cleanupInterval = setInterval(() => {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (now - session.lastAccessed > SESSION_TTL_MS) {
      sessions.delete(id);
    }
  }
}, 10 * 60 * 1000);
cleanupInterval.unref();

/**
 * Return true if the session has exceeded its TTL.
 * Used by the session adapter to fail-closed on expired sessions, and by
 * getSession() to proactively reject them between cleanup sweeps.
 */
export function isSessionExpired(session: ApiSession): boolean {
  return Date.now() - session.lastAccessed > SESSION_TTL_MS;
}

/** Retrieve an existing session, refreshing its TTL.
 * Returns undefined if the session does not exist or has expired. */
export function getSession(sessionId: string): ApiSession | undefined {
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  if (isSessionExpired(session)) {
    sessions.delete(sessionId);
    return undefined;
  }
  session.lastAccessed = Date.now();
  return session;
}

export function getPrincipalId(
  request: { headers: { get(name: string): string | undefined | null } },
): string | undefined {
  return request.headers.get("x-ms-client-principal-id")?.trim() || undefined;
}

export function isSessionOwnedBy(session: ApiSession, principalId?: string): boolean {
  if (!session.principalId) return true;
  if (!principalId) return false;
  return session.principalId === principalId;
}

export function adoptSessionPrincipal(session: ApiSession, principalId?: string): void {
  if (!session.principalId && principalId) {
    session.principalId = principalId;
  }
}

/** Create a new session with Discover-phase system prompt. */
export function createSession(principalId?: string): ApiSession {
  const sessionId = randomUUID();
  const now = new Date().toISOString();

  const systemPrompt = buildSystemPrompt({
    phase: Phase.Discover,
    appDefinition: {},
  });

  const session: ApiSession = {
    state: {
      sessionId,
      currentPhase: Phase.Discover,
      createdAt: now,
      updatedAt: now,
      appDefinition: {},
      messages: [
        { role: "system", content: systemPrompt, timestamp: now },
      ],
    },
    lastAccessed: Date.now(),
    generatedArtifacts: [],
    usageHistory: [],
    principalId,
    routingPhaseTrusted: true,
    setupGenerationTrusted: false,
    deployState: {
      stage: "idle",
      updatedAt: now,
    },
    costEstimateCache: new Map(),
  };

  sessions.set(sessionId, session);
  return session;
}

/**
 * Client-provided message for session hydration.
 * Only role + content — the server never trusts client timestamps or system prompts.
 */
export interface ClientMessage {
  role: "user" | "assistant";
  content: string;
  phase?: string;
  usage?: TurnUsage;
  setupGeneration?: SetupGenerationSnapshot;
  /** Optional compact artifact-bearing A2UI payloads for cold-start rehydration. */
  a2uiMessages?: unknown[];
}

/**
 * Create a new session and seed it with client-provided conversation history.
 * Used when the in-memory session has been lost (cold start / scale event)
 * but the client still holds the message history in React state.
 *
 * System messages are always rebuilt server-side — client-sent system
 * messages are silently dropped.
 */
export function hydrateSession(clientMessages: ClientMessage[], principalId?: string): ApiSession {
  const session = createSession(principalId);
  const now = new Date().toISOString();
  session.routingPhaseTrusted = false;
  let latestSetupGeneration: SetupGenerationRunState | undefined;

  for (const msg of clientMessages) {
    // Only allow user/assistant — never trust client-sent system prompts
    if (msg.role !== "user" && msg.role !== "assistant") continue;
    if (!msg.content) continue;

    session.state.messages.push({
      role: msg.role,
      content: msg.content,
      timestamp: now,
    });

    // Rebuild generatedArtifacts from assistant messages containing FileEditor components.
    // Prefer the compact A2UI payloads sent by the client; fall back to legacy
    // JSON-envelope parsing for older persisted sessions.
    if (msg.role === "assistant") {
      if (Array.isArray(msg.a2uiMessages) && msg.a2uiMessages.length > 0) {
        for (const artifact of extractArtifactsFromA2UI(msg.a2uiMessages)) {
          upsertArtifact(session.generatedArtifacts, artifact);
        }
      } else {
        rebuildArtifactsFromMessage(msg.content, session.generatedArtifacts);
      }
      if (isTurnUsage(msg.usage)) {
        session.usageHistory.push(msg.usage);
      }
      if (isValidSetupGenerationSnapshot(msg.setupGeneration)) {
        latestSetupGeneration = cloneSetupGenerationRun(msg.setupGeneration.run);
        for (const generatedFile of latestSetupGeneration.generatedFiles) {
          upsertArtifact(
            session.generatedArtifacts,
            extractArtifactMetadata(
              generatedFile.path,
              generatedFile.language,
              "",
            ),
          );
        }
      }
    }
  }

  // Restore current phase from the last message that carries a valid phase tag.
  const phases = new Set(Object.values(Phase));
  const lastPhase = [...clientMessages]
    .reverse()
    .find((msg) => typeof msg.phase === "string" && phases.has(msg.phase as Phase))
    ?.phase as Phase | undefined;
  session.state.currentPhase = lastPhase ?? Phase.Discover;

  session.state.updatedAt = now;
  if (latestSetupGeneration) {
    session.setupGenerationRun = latestSetupGeneration;
    session.setupGenerationTrusted = true;
  }
  return session;
}

/** Max number of artifacts tracked to prevent unbounded growth. */
export const MAX_TRACKED_ARTIFACTS = 50;

/** Infer language from filename extension. */
export function inferLanguage(filename: string): string {
  const baseName = filename.split(/[\\/]/).pop() ?? filename;
  const ext = baseName.includes(".") ? (baseName.split(".").pop() ?? "") : baseName;
  const langMap: Record<string, string> = {
    ts: "typescript", js: "javascript", py: "python", go: "go",
    rs: "rust", java: "java", cs: "csharp", bicep: "bicep",
    yaml: "yaml", yml: "yaml", json: "json", md: "markdown",
    dockerfile: "dockerfile", sh: "shell",
  };
  return langMap[ext.toLowerCase()] ?? ext;
}

/** Extract metadata from file content at upsert time — never stores the content. */
export function extractArtifactMetadata(
  filename: string,
  language: string,
  content: string,
): GeneratedArtifact {
  const bicepResources: string[] = [];
  const k8sResources: string[] = [];

  if (filename.endsWith(".bicep")) {
    const re = /resource\s+(\w+)\s+'(Microsoft\.[^'@]+)@/g;
    let m;
    while ((m = re.exec(content)) !== null) {
      bicepResources.push(`${m[1]} (${m[2]})`);
    }
  }

  if (filename.endsWith(".yaml") || filename.endsWith(".yml")) {
    const docs = content.split(/^---$/m);
    for (const doc of docs) {
      const kindMatch = doc.match(/kind:\s*(\w+)/);
      const nameMatch = doc.match(/name:\s*["']?([a-z0-9][-a-z0-9]*)["']?/m);
      if (kindMatch) {
        k8sResources.push(kindMatch[1] + (nameMatch ? ": " + nameMatch[1] : ""));
      }
    }
  }

  return { filename, language: language || inferLanguage(filename), bicepResources, k8sResources };
}

/** Upsert an artifact into the list — keep the most recent entries, capped at MAX_TRACKED_ARTIFACTS. */
export function upsertArtifact(list: GeneratedArtifact[], artifact: GeneratedArtifact): void {
  const idx = list.findIndex((a) => a.filename === artifact.filename);

  if (idx >= 0) {
    list.splice(idx, 1);
  } else if (list.length >= MAX_TRACKED_ARTIFACTS) {
    list.shift();
  }

  list.push(artifact);
}

/**
 * Extract FileEditor metadata from A2UI updateComponents messages.
 * Used both during a live turn (converse.ts) and when rebuilding
 * artifacts during session hydration.
 */
export function extractArtifactsFromA2UI(
  a2uiMessages: unknown[],
): GeneratedArtifact[] {
  const artifacts: GeneratedArtifact[] = [];
  for (const msg of a2uiMessages) {
    if (!msg || typeof msg !== "object") continue;
    const components = (msg as { updateComponents?: { components?: unknown[] } }).updateComponents?.components;
    if (!Array.isArray(components)) continue;
    for (const comp of components) {
      artifacts.push(...extractArtifactsFromComponent(comp));
    }
  }
  return artifacts;
}

function extractArtifactsFromComponent(component: unknown): GeneratedArtifact[] {
  if (!component || typeof component !== "object" || Array.isArray(component)) {
    return [];
  }

  const candidate = component as Record<string, unknown>;
  if (candidate.component !== "FileEditor") {
    return [];
  }

  const rawEntries = Array.isArray(candidate.files) && candidate.files.length > 0
    ? candidate.files
    : [candidate];

  return rawEntries
    .map((entry) => normalizeArtifactEntry(entry))
    .filter((entry): entry is GeneratedArtifact => entry !== null);
}

function normalizeArtifactEntry(entry: unknown): GeneratedArtifact | null {
  if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
    return null;
  }

  const record = entry as Record<string, unknown>;
  const filename = coerceString(record.filename)
    ?? coerceString(record.path)
    ?? coerceString(record.artifactPath);
  if (!filename) {
    return null;
  }

  const language = coerceString(record.language) ?? inferLanguage(filename);
  const content = coerceString(record.content) ?? "";
  return extractArtifactMetadata(filename, language, content);
}

function coerceString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim().length > 0 ? value : undefined;
}

/**
 * Scan a message (raw JSON or A2UI content) for FileEditor components
 * and upsert any found artifacts into the list.
 */
/** Max content length to attempt JSON.parse on during hydration (prevent DoS). */
const MAX_HYDRATION_CONTENT_LENGTH = 100_000; // 100KB max per message

function rebuildArtifactsFromMessage(
  content: string,
  artifacts: GeneratedArtifact[],
): void {
  if (content.length > MAX_HYDRATION_CONTENT_LENGTH) return;

  // Match FileEditor components in assistant messages — these appear in
  // A2UI updateComponents payloads as JSON objects with component:"FileEditor"
  const fileEditorPattern = /"component"\s*:\s*"FileEditor"/;
  if (!fileEditorPattern.test(content)) return;

  try {
    const parsed = JSON.parse(content) as Record<string, unknown>;
    const a2ui = parsed.a2ui as Array<{ updateComponents?: { components: unknown[] } }> | undefined;
    if (!Array.isArray(a2ui)) return;

    for (const artifact of extractArtifactsFromA2UI(a2ui)) {
      upsertArtifact(artifacts, artifact);
    }
  } catch {
    // Content isn't valid JSON — skip silently
  }
}

/** Append a message to the session's history. */
export function addMessage(
  sessionId: string,
  role: ConversationMessage["role"],
  content: string,
): void {
  const session = sessions.get(sessionId);
  if (!session) return;
  session.state.messages.push({
    role,
    content,
    timestamp: new Date().toISOString(),
  });
  session.state.updatedAt = new Date().toISOString();
  session.lastAccessed = Date.now();
}

export function recordUsage(
  sessionId: string,
  usage: TurnUsage,
): UsageSummary | undefined {
  const session = sessions.get(sessionId);
  if (!session) return undefined;

  session.usageHistory.push(usage);
  session.state.updatedAt = new Date().toISOString();
  session.lastAccessed = Date.now();

  return buildUsageSummary(usage, session.usageHistory);
}

function isTurnUsage(value: unknown): value is TurnUsage {
  if (!value || typeof value !== "object") return false;
  const usage = value as Partial<TurnUsage>;
  return typeof usage.model === "string"
    && typeof usage.recordedAt === "string"
    && typeof usage.inputTokens === "number"
    && typeof usage.outputTokens === "number"
    && typeof usage.totalTokens === "number"
    && (usage.costStatus === "estimated" || usage.costStatus === "unavailable");
}
