/**
 * @module @kickstart/api/lib/session-store
 *
 * In-memory session store with TTL cleanup.
 * Stores conversation state for the web surface API.
 */

import { randomUUID } from "node:crypto";
import {
  Phase,
  createInitialState,
  buildSystemPrompt,
} from "@kickstart/core";
import type {
  SessionState,
  ConversationState,
  ConversationMessage,
} from "@kickstart/core";

/** Metadata for a file generated by the LLM, tracked across turns.
 *  Stores only what's needed for summaries — never full file content. */
export interface GeneratedArtifact {
  filename: string;
  language: string;
  /** Bicep resource declarations, e.g. ["myCluster (Microsoft.ContainerService/managedClusters)"] */
  bicepResources: string[];
  /** K8s resource declarations, e.g. ["Deployment: my-app"] */
  k8sResources: string[];
}

export interface DeployCostGateState {
  acknowledgedAt: string;
  estimatedMonthlyTotal: number;
  currency: string;
  source: string;
}

export interface DeployErrorState {
  code: string;
  message: string;
  actionableSteps?: string[];
  retryable?: boolean;
}

export type DeployStage = "idle" | "cost-gated" | "target-selected" | "deploying" | "succeeded" | "failed";

export interface DeployState {
  stage: DeployStage;
  updatedAt: string;
  costGate?: DeployCostGateState;
  activeRunId?: string;
  deploymentName?: string;
  appUrl?: string;
  lastError?: DeployErrorState;
}

type AuditEventValue = string | number | boolean | null;

export interface AuditEvent {
  readonly id: string;
  readonly timestamp: string;
  readonly type: string;
  readonly sessionId: string;
  readonly ownerPrincipalId?: string;
  readonly actorPrincipalId?: string;
  readonly details?: Readonly<Record<string, AuditEventValue>>;
}

/** Session wrapper with engine state and TTL tracking. */
export interface ApiSession {
  state: SessionState;
  engineState: ConversationState;
  lastAccessed: number;
  /** Tracks files generated by the LLM across turns for artifact summary. */
  generatedArtifacts: GeneratedArtifact[];
  /** SWA principal that owns this session. */
  ownerPrincipalId?: string;
  /** Thin deployment state for the real Azure happy path. */
  deployState: DeployState;
  /** Append-only audit trail for security-sensitive session changes. */
  auditEvents: ReadonlyArray<AuditEvent>;
}

const sessions = new Map<string, ApiSession>();

/** Session TTL: 1 hour. */
const SESSION_TTL_MS = 60 * 60 * 1000;

/** Purge stale sessions every 10 minutes. */
const cleanupInterval = setInterval(() => {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (now - session.lastAccessed > SESSION_TTL_MS) {
      sessions.delete(id);
    }
  }
}, 10 * 60 * 1000);
cleanupInterval.unref();

/** Retrieve an existing session, refreshing its TTL. */
export function getSession(sessionId: string): ApiSession | undefined {
  const session = sessions.get(sessionId);
  if (session) session.lastAccessed = Date.now();
  return session;
}

export function getPrincipalId(
  request: { headers: { get(name: string): string | undefined | null } },
): string | undefined {
  return request.headers.get("x-ms-client-principal-id")?.trim() || undefined;
}

export function isSessionOwnedBy(session: ApiSession, principalId?: string): boolean {
  if (!session.ownerPrincipalId || !principalId) return false;
  return session.ownerPrincipalId === principalId;
}

export function adoptSessionPrincipal(session: ApiSession, principalId?: string): void {
  if (!session.ownerPrincipalId && principalId) {
    session.ownerPrincipalId = principalId;
  }
}

export function appendAuditEvent(
  session: ApiSession,
  event: {
    type: string;
    actorPrincipalId?: string;
    details?: Record<string, AuditEventValue>;
  },
): void {
  const details = event.details ? Object.freeze({ ...event.details }) : undefined;
  const auditEvent = Object.freeze({
    id: randomUUID(),
    timestamp: new Date().toISOString(),
    type: event.type,
    sessionId: session.state.sessionId,
    ownerPrincipalId: session.ownerPrincipalId,
    actorPrincipalId: event.actorPrincipalId,
    ...(details ? { details } : {}),
  }) as AuditEvent;

  session.auditEvents = [...session.auditEvents, auditEvent];
}

/** Create a new session with Discover-phase system prompt. */
export function createSession(ownerPrincipalId?: string): ApiSession {
  const sessionId = randomUUID();
  const now = new Date().toISOString();
  const engineState = createInitialState();

  const systemPrompt = buildSystemPrompt({
    phase: Phase.Discover,
    appDefinition: {},
  });

  const session: ApiSession = {
    state: {
      sessionId,
      currentPhase: Phase.Discover,
      createdAt: now,
      updatedAt: now,
      appDefinition: {},
      messages: [
        { role: "system", content: systemPrompt, timestamp: now },
      ],
    },
    engineState,
    lastAccessed: Date.now(),
    generatedArtifacts: [],
    ownerPrincipalId,
    deployState: {
      stage: "idle",
      updatedAt: now,
    },
    auditEvents: [],
  };

  sessions.set(sessionId, session);
  return session;
}

/**
 * Client-provided message for session hydration.
 * Only role + content — the server never trusts client timestamps or system prompts.
 */
export interface ClientMessage {
  role: "user" | "assistant";
  content: string;
}

/**
 * Create a new session and seed it with client-provided conversation history.
 * Used when the in-memory session has been lost (cold start / scale event)
 * but the client still holds the message history in React state.
 *
 * System messages are always rebuilt server-side — client-sent system
 * messages are silently dropped.
 */
export function hydrateSession(clientMessages: ClientMessage[], ownerPrincipalId?: string): ApiSession {
  const session = createSession(ownerPrincipalId);
  const now = new Date().toISOString();

  for (const msg of clientMessages) {
    // Only allow user/assistant — never trust client-sent system prompts
    if (msg.role !== "user" && msg.role !== "assistant") continue;
    if (!msg.content) continue;

    session.state.messages.push({
      role: msg.role,
      content: msg.content,
      timestamp: now,
    });

    // Rebuild generatedArtifacts from assistant messages containing FileEditor components
    if (msg.role === "assistant") {
      rebuildArtifactsFromMessage(msg.content, session.generatedArtifacts);
    }
  }

  session.state.updatedAt = now;
  return session;
}

/** Max number of artifacts tracked to prevent unbounded growth. */
export const MAX_TRACKED_ARTIFACTS = 50;

/** Infer language from filename extension. */
export function inferLanguage(filename: string): string {
  const ext = filename.split(".").pop() ?? "";
  const langMap: Record<string, string> = {
    ts: "typescript", js: "javascript", py: "python", go: "go",
    rs: "rust", java: "java", cs: "csharp", bicep: "bicep",
    yaml: "yaml", yml: "yaml", json: "json", md: "markdown",
    dockerfile: "dockerfile", sh: "shell",
  };
  return langMap[ext.toLowerCase()] ?? ext;
}

/** Extract metadata from file content at upsert time — never stores the content. */
export function extractArtifactMetadata(
  filename: string,
  language: string,
  content: string,
): GeneratedArtifact {
  const bicepResources: string[] = [];
  const k8sResources: string[] = [];

  if (filename.endsWith(".bicep")) {
    const re = /resource\s+(\w+)\s+'(Microsoft\.[^'@]+)@/g;
    let m;
    while ((m = re.exec(content)) !== null) {
      bicepResources.push(`${m[1]} (${m[2]})`);
    }
  }

  if (filename.endsWith(".yaml") || filename.endsWith(".yml")) {
    const docs = content.split(/^---$/m);
    for (const doc of docs) {
      const kindMatch = doc.match(/kind:\s*(\w+)/);
      const nameMatch = doc.match(/name:\s*["']?([a-z0-9][-a-z0-9]*)["']?/m);
      if (kindMatch) {
        k8sResources.push(kindMatch[1] + (nameMatch ? ": " + nameMatch[1] : ""));
      }
    }
  }

  return { filename, language: language || inferLanguage(filename), bicepResources, k8sResources };
}

/** Upsert an artifact into the list — keep the most recent entries, capped at MAX_TRACKED_ARTIFACTS. */
export function upsertArtifact(list: GeneratedArtifact[], artifact: GeneratedArtifact): void {
  const idx = list.findIndex((a) => a.filename === artifact.filename);

  if (idx >= 0) {
    list.splice(idx, 1);
  } else if (list.length >= MAX_TRACKED_ARTIFACTS) {
    list.shift();
  }

  list.push(artifact);
}

/**
 * Extract FileEditor metadata from A2UI updateComponents messages.
 * Used both during a live turn (converse.ts) and when rebuilding
 * artifacts during session hydration.
 */
export function extractArtifactsFromA2UI(
  a2uiMessages: Array<{ updateComponents?: { components: unknown[] } }>,
): GeneratedArtifact[] {
  const artifacts: GeneratedArtifact[] = [];
  for (const msg of a2uiMessages) {
    if (!msg.updateComponents?.components) continue;
    for (const comp of msg.updateComponents.components) {
      const c = comp as Record<string, unknown>;
      if (c.component === "FileEditor" && typeof c.filename === "string") {
        const artifact = extractArtifactMetadata(
          c.filename,
          typeof c.language === "string" ? c.language : "",
          typeof c.content === "string" ? c.content : "",
        );
        artifacts.push(artifact);
      }
    }
  }
  return artifacts;
}

/**
 * Scan a message (raw JSON or A2UI content) for FileEditor components
 * and upsert any found artifacts into the list.
 */
/** Max content length to attempt JSON.parse on during hydration (prevent DoS). */
const MAX_HYDRATION_CONTENT_LENGTH = 100_000; // 100KB max per message

function rebuildArtifactsFromMessage(
  content: string,
  artifacts: GeneratedArtifact[],
): void {
  if (content.length > MAX_HYDRATION_CONTENT_LENGTH) return;

  // Match FileEditor components in assistant messages — these appear in
  // A2UI updateComponents payloads as JSON objects with component:"FileEditor"
  const fileEditorPattern = /"component"\s*:\s*"FileEditor"/;
  if (!fileEditorPattern.test(content)) return;

  try {
    const parsed = JSON.parse(content) as Record<string, unknown>;
    const a2ui = parsed.a2ui as Array<{ updateComponents?: { components: unknown[] } }> | undefined;
    if (!Array.isArray(a2ui)) return;

    for (const artifact of extractArtifactsFromA2UI(a2ui)) {
      upsertArtifact(artifacts, artifact);
    }
  } catch {
    // Content isn't valid JSON — skip silently
  }
}

/** Append a message to the session's history. */
export function addMessage(
  sessionId: string,
  role: ConversationMessage["role"],
  content: string,
): void {
  const session = sessions.get(sessionId);
  if (!session) return;
  session.state.messages.push({
    role,
    content,
    timestamp: new Date().toISOString(),
  });
  session.state.updatedAt = new Date().toISOString();
  session.lastAccessed = Date.now();
}
