import type { A2UIMessageV09 as A2UIMessage } from './a2ui.js';
import type { AgentInputItem } from '@openai/agents';

export interface AppIntent {
  id?: string;
  summary?: string;
  [key: string]: unknown;
}

export interface Artifact {
  path: string;
  kind?: string;
  metadata?: Record<string, unknown>;
}

export interface A2UICatalog {
  id: string;
  components?: readonly string[];
  userActions?: readonly string[];
}

export interface Turn {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content?: string;
  timestamp?: string;
  /**
   * Trust marker for the origin of this turn (#1074 M3).
   *
   *  - `'server'` (default, implicit when absent): the turn was authored by
   *    the server — either a sanitized live user message or an assistant
   *    response generated by the runner on this server instance.
   *  - `'client-hydrated'`: the turn was replayed by the client on a brand-new
   *    (cold-start) session via `POST /api/converse { messages: [...] }`. The
   *    runner must render these inside a delimited "untrusted context" block
   *    rather than interleaving them with server-authored history, so the
   *    LLM and any downstream auditor can tell client-replayed context from
   *    server-authored context.
   */
  trust?: 'server' | 'client-hydrated';
}

/**
 * A paired tool call + result record captured within a turn (#103).
 *
 * Stored in `Session.toolCallItems` so the model retains context about prior
 * tool actions across turns. The `callItem` is a `function_call` AgentInputItem
 * and `resultItem` is the corresponding `function_call_result`. Both are
 * verbatim SDK items captured from `run_item_stream_event`.
 */
export interface ToolCallRecord {
  callItem: AgentInputItem;
  resultItem?: AgentInputItem;
}

/**
 * Shape of a single message accepted by `POST /api/converse { messages: [...] }`
 * for cold-session hydration (#1074 D3). The client carefully assembles prior
 * chat history from local state and ships it on every request so that a
 * function cold-start does not leave the server without context.
 *
 * Only `user` and `assistant` roles are accepted — `tool` / `system` turns are
 * not trustable from a client and are rejected at the schema boundary
 * (Zapp M1).
 */
export interface ClientHydrationMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface PendingUserAction {
  name: string;
  runId?: string;
  resultSchema?: unknown;
  issuedAt?: string;
}

// TODO(Step 3): Replace with the real Azure Identity credential contract.
export type AzureCredential = unknown;

export interface SessionCtx {
  sessionId: string;
  user: {
    tid?: string;
    oid?: string;
    upn?: string;
  };
  intent: AppIntent | null;
  artifacts: Map<string, Artifact>;
  a2uiEmissions: A2UIMessage[];
  /**
   * Live surface IDs known to have an outstanding `createSurface` within this
   * session. Used by `core.emit_ui` to enforce idempotent surface lifecycle
   * (D11, #1075): reject duplicate `createSurface` and reject
   * `updateComponents` / `updateDataModel` / `deleteSurface` targeting a
   * surface that has not been created. Transient; not persisted across
   * session restart. Bounded by `maxLiveSurfaces`.
   */
  liveSurfaceIds: Set<string>;
  /**
   * Upper bound on `liveSurfaceIds.size`. Resolved once at harness module
   * load from `KICKSTART_MAX_LIVE_SURFACES` (default 1000, clamped
   * [10, 100000]). Enforced in `core.emit_ui` on `createSurface` to guard
   * against runaway in-memory growth (Zapp M1, #1075).
   */
  readonly maxLiveSurfaces: number;
  negotiatedCatalog: A2UICatalog;
  recentTurns: Turn[];
  activeAgent: string;
  pendingUserAction: PendingUserAction | null;
  /**
   * Per-turn record of skills pulled by `core.read_skill`. Reset at the top
   * of every `Runner.run` turn inside a try/finally. See `SkillTrackingCtx`
   * in `pack-core/src/tools/read_skill.ts` for the narrow consumer view.
   * Optional on the interface so unrelated consumers need not populate it.
   */
  skillsPulled?: Set<string>;
  skillsPulledBytes?: number;
  skillsPulledTokens?: number;
  /**
   * Paired tool call + result items captured during each turn (#103).
   * Bounded to the last 200 pairs (same window as recentTurns).
   * Used by `toAgentInputItems` to replay tool context across turns.
   */
  toolCallItems: ToolCallRecord[];
  recordA2UIEmission(msg: A2UIMessage): void;
  recordArtifact(artifact: Artifact): void;
  recordTurn(turn: Turn): void;
  recordToolCallRecord(record: ToolCallRecord): void;
  getAzureCreds(): Promise<AzureCredential>;
  // TODO(Step 3): Replace with a typed token/result contract once resume/runtime wiring lands.
  getGithubToken(): Promise<unknown>;
}
