import type { A2UIMessageV09 as A2UIMessage } from './a2ui.js';

export interface AppIntent {
  id?: string;
  summary?: string;
  [key: string]: unknown;
}

export interface Artifact {
  path: string;
  kind?: string;
  metadata?: Record<string, unknown>;
}

export interface A2UICatalog {
  id: string;
  components?: readonly string[];
  userActions?: readonly string[];
}

export interface Turn {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content?: string;
  timestamp?: string;
  /**
   * Trust marker for the origin of this turn (#1074 M3).
   *
   *  - `'server'` (default, implicit when absent): the turn was authored by
   *    the server — either a sanitized live user message or an assistant
   *    response generated by the runner on this server instance.
   *  - `'client-hydrated'`: the turn was replayed by the client on a brand-new
   *    (cold-start) session via `POST /api/converse { messages: [...] }`. The
   *    runner must render these inside a delimited "untrusted context" block
   *    rather than interleaving them with server-authored history, so the
   *    LLM and any downstream auditor can tell client-replayed context from
   *    server-authored context.
   */
  trust?: 'server' | 'client-hydrated';
}

/**
 * Shape of a single message accepted by `POST /api/converse { messages: [...] }`
 * for cold-session hydration (#1074 D3). The client carefully assembles prior
 * chat history from local state and ships it on every request so that a
 * function cold-start does not leave the server without context.
 *
 * Only `user` and `assistant` roles are accepted — `tool` / `system` turns are
 * not trustable from a client and are rejected at the schema boundary
 * (Zapp M1).
 */
export interface ClientHydrationMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface PendingUserAction {
  name: string;
  runId?: string;
  resultSchema?: unknown;
  issuedAt?: string;
}

// TODO(Step 3): Replace with the real Azure Identity credential contract.
export type AzureCredential = unknown;

export interface SessionCtx {
  sessionId: string;
  user: {
    tid?: string;
    oid?: string;
    upn?: string;
  };
  intent: AppIntent | null;
  artifacts: Map<string, Artifact>;
  a2uiEmissions: A2UIMessage[];
  negotiatedCatalog: A2UICatalog;
  recentTurns: Turn[];
  activeAgent: string;
  pendingUserAction: PendingUserAction | null;
  recordA2UIEmission(msg: A2UIMessage): void;
  recordArtifact(artifact: Artifact): void;
  recordTurn(turn: Turn): void;
  getAzureCreds(): Promise<AzureCredential>;
  // TODO(Step 3): Replace with a typed token/result contract once resume/runtime wiring lands.
  getGithubToken(): Promise<unknown>;
}
